### ISSUE TITLE
Attaching Firebase as a Backend

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#10]
As of now backend is not attached to the app. We can use Firebase as a backend. Please assign this issue to me under SWOC.

**Comment by avinashkranjan** [comment]
Assigned to you @HimeshNayak

**Comment by HimeshNayak** [comment]
Should I make a firebase project with my email or would you create one and add me as a collaborator?

**Comment by avinashkranjan** [comment]
I'll add you as collaborator.. forward me your mail id

**Comment by HimeshNayak** [comment]
Okay great! Its himeshnayak015@gmail.com

**Comment by avinashkranjan** [comment]
Added You as Editor @HimeshNayak
