### ISSUE TITLE
Without verified log-in User can navigate to the onboarding page

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#101]
**Is your feature request related to a problem? Please describe.**
Yes, If any user completes the signup and signup additional details page and instead of log-in if the user closes the app and then reopens the app, the log-in page not come....directly navigate to the bottom navigation page ..... So, if any user gives an invalid email or not verify their email, they can also navigate to the onboarding page...... So here auth break.....

**Describe the solution you'd like**
Some modification about some logical navigation needed here.....

**Describe alternatives you've considered**
I think I can solve this issue.....this is a mistake

**Additional context**
If I can forward that...please assign me to here... I am also a gssoc'21 participant.... Thank u @HimeshNayak  @avinashkranjan

**Comment by D-Ajay-Kumar** [comment]
Nice catch man, the problem really does exist.

**Comment by SamarpanCoder2002** [comment]
> Nice catch man, the problem really does exist.

Yaah.... prb catchup at the time of debugging

**Comment by HimeshNayak** [comment]
go ahead @SamarpanCoder2002 ! I'll assign this issue to you.

**Comment by SamarpanCoder2002** [comment]
> go ahead @SamarpanCoder2002 ! I'll assign this issue to you.

Thank u @HimeshNayak

**Comment by SamarpanCoder2002** [comment]
I already added pull request #105 related to that issue... please review it @HimeshNayak and merge it @avinashkranjan
