### ISSUE TITLE
Adding google meet and zoom links to join any class immediatly

### ISSUE THREAD

**Issue by Adityakarthik18** [avinashkranjan/Friday#103]
]

**Comment by avinashkranjan** [comment]
No Description ?? @Adityakarthik18

**Comment by LayaMitta** [comment]
I am a GSSOC'21 participant, can I work on this issue?

**Comment by avinashkranjan** [comment]
Hey @Adityakarthik18 Would you like to work on it..Or should I assign this to someone else??

**Comment by Adityakarthik18** [comment]
Sir i want to do it sir but i can't find the website of this project to do
it sir!
html css files are not there in that are.
Thanking you sir!

**Comment by avinashkranjan** [comment]
Hey @Adityakarthik18 It's and Android/iOS app not a Web App

**Comment by Adityakarthik18** [comment]
no sir i am not working i thought it is web app

**Comment by nicks101** [comment]
Can I work on this issue?

**Comment by Adityakarthik18** [comment]
Ya i have told them that i am not interested then will assign to some one
ask them

**Comment by avinashkranjan** [comment]
Sure Go Ahead @nicks101

**Comment by nicks101** [comment]
I've added a property `joinLink` in the `classes` model. 
For the UI, in the classes screen, there's the text for `join now`. Clicking on this will open the URL of the class if it exists.

Let me know if there are any changes for logic or UI.

![Screenshot_1616408211](https://user-images.githubusercontent.com/32807816/111975358-85847280-8b26-11eb-8eb9-2bd784d47660.png)
