### ISSUE TITLE
Errors in Documentation - Improve the README by adding some new sections and removing errors

### ISSUE THREAD

**Issue by devTejas** [avinashkranjan/Friday#104]
**Describe the bug**
Hello team, I have found some errors in the documentation and would like to improve them. I even feel the need of adding some new sections to the _Readme_ file such that it helps new developers in understanding more about the app technically.

**Screenshots**
I have used _Grammarly_ to find errors in the existing _readme_. Please check the below screenshots for better understanding.
![Screenshot (206)](https://user-images.githubusercontent.com/55909123/111586518-f5bd8c00-87e6-11eb-8b13-ba0bdd3b3aa0.png)
![Screenshot (207)](https://user-images.githubusercontent.com/55909123/111586522-f6eeb900-87e6-11eb-88f4-a0ce12d05544.png)

**Additional context**
I would like to improve the _readme_ by removing the errors and add some new sections such as Features , Updates and Resources that can help new developers understand better about the project.
Please assign me to here. I am a gssoc'21 participant. Thank u @HimeshNayak  @avinashkranjan

**Comment by LayaMitta** [comment]
I am a GSSOC'21 participant, can I work on this issue?

**Comment by avinashkranjan** [comment]
Go Ahead @devTejas

**Comment by Abhinav-B-19** [comment]
I am a GSSOC'21 participant, can I improve the REAADME file.

**Comment by Bhumika2409** [comment]
I am a GSSOC'21 participant, can I fix the grammatical issues and make the README file more comprehensive.

**Comment by harshita2319** [comment]
I'd like to work on this issue! (GSSOC participant)
