### ISSUE TITLE
Adding edit profile feature

### ISSUE THREAD

**Issue by GayatriMunde** [avinashkranjan/Friday#106]
The academic year and age are not not the constant things, they changes over a period of time. 

To resolve this, one feature of editing profile can be added to the profile section of user.

**Comment by HimeshNayak** [comment]
Hey @GayatriMunde! This a much needed feature. If you want to work on this issue under GSSOC21, please comment and I'll assign it to you.

**Comment by GayatriMunde** [comment]
Yes. I would like to work on this.

**Comment by HimeshNayak** [comment]
Okay, go ahead. I'll assign it to you.

**Comment by HimeshNayak** [comment]
Any updates? @GayatriMunde

**Comment by rakshitkamboj** [comment]
@HimeshNayak Can I Work on this issue if no one is working on this issue.

**Comment by HimeshNayak** [comment]
@GayatriMunde has been given a deadline till tomorrow. If @GayatriMunde is unable to submit a PR, it would be assigned to @rakshitkamboj

**Comment by rakshitkamboj** [comment]
@HimeshNayak Can u please assign this issue to me. As deadline was till yesterday for submitting the PR.
I will start working on this as soon as you assign it to me.
Thanks.

**Comment by HimeshNayak** [comment]
Go ahead @rakshitkamboj! All the best! Happy Coding!

**Comment by rakshitkamboj** [comment]
@HimeshNayak Can you please give me some idea about editable profile like should I create a button after clicking on that a screen or buttomsheet will appear in which user can edit our age and academic year 
OR
should I provide separate button for age and year.
What do you think about this?

**Comment by HimeshNayak** [comment]
> @HimeshNayak Can you please give me some idea about editable profile like should I create a button after clicking on that a screen or buttomsheet will appear in which user can edit our age and academic year
> OR
> should I provide separate button for age and year.
> What do you think about this?

I think an edit button should be there which will open will make the fields editable (i.e, widgets will be replaced by editable widgets) and then you can submit the data to the DB.
Sounds good? If you have any other ideas do share.

**Comment by rakshitkamboj** [comment]
@HimeshNayak Yeah sounds good! 
So, I have to apply this for every Text field (like -name, college ) Or just age and academic year?

**Comment by HimeshNayak** [comment]
> @HimeshNayak Yeah sounds good!
> So, I have to apply this for every Text field (like -name, college ) Or just age and academic year?

Make all the fields editable except college details (as that is complex and would be taken up in a different issue), as when the user is entering the details in the signup page, he might make a spelling mistake and wishes to correct it later (in the case of name).

**Comment by rakshitkamboj** [comment]
Okay I got it.
I will try to apply changes as soon as possible and I will send you a demo video of same.
Thanks @HimeshNayak .

**Comment by rakshitkamboj** [comment]
@HimeshNayak I am trying to update users data in profile section but as soon as I re-run the app from studio its changes back to same . I think I am not able update it in database properly .
Can you help me in that?

**Comment by rakshitkamboj** [comment]
https://user-images.githubusercontent.com/69065683/113605881-e3f03b80-9664-11eb-9635-3c18d7d27a8c.mp4

**Comment by HimeshNayak** [comment]
Hey @rakshitkamboj, I am here to help. Just make a PR so that I can review the code and figure out the problem.

**Comment by rakshitkamboj** [comment]
@HimeshNayak Appreciable.
Sure I will make one.

**Comment by anotherwebguy** [comment]
Hey i can work on this issue @HimeshNayak 
I've already made an layout for profile screen if u would like i can work on it under gssoc
Plz assign me this issue
![Screenshot_2021-04-08-07-03-50-767_com iqonic prokitflutter](https://user-images.githubusercontent.com/66346161/113955037-9fb59480-9838-11eb-8ab9-fa23f3a8f105.jpg)
![Screenshot_2021-04-08-07-03-34-773_com iqonic prokitflutter](https://user-images.githubusercontent.com/66346161/113955041-a17f5800-9838-11eb-9a92-3e2a9cf5251a.jpg)

**Comment by HimeshNayak** [comment]
@

> Hey i can work on this issue @HimeshNayak
> I've already made an layout for profile screen if u would like i can work on it under gssoc
> Plz assign me this issue
> ![Screenshot_2021-04-08-07-03-50-767_com iqonic prokitflutter](https://user-images.githubusercontent.com/66346161/113955037-9fb59480-9838-11eb-8ab9-fa23f3a8f105.jpg)
> ![Screenshot_2021-04-08-07-03-34-773_com iqonic prokitflutter](https://user-images.githubusercontent.com/66346161/113955041-a17f5800-9838-11eb-9a92-3e2a9cf5251a.jpg)

These are great @anotherwebguy. I would suggest that let @rakshitkamboj work on the implementation part and then you can work on the UI in another issue.

**Comment by anotherwebguy** [comment]
yeah that's fine @HimeshNayak  so should i make a pr for this ui and then after that @rakshitkamboj can do the implementation of pushing the changes in profile to firebase and also the retreiving part from firebase ?

**Comment by HimeshNayak** [comment]
> yeah that's fine @HimeshNayak so should i make a pr for this ui and then after that @rakshitkamboj can do the implementation of pushing the changes in profile to firebase and also the retreiving part from firebase ?

Let him complete the backend work first and then the UI can be changed, also let @avinashkranjan and @hareshnayak approve the UI first.

**Comment by anotherwebguy** [comment]
> > yeah that's fine @HimeshNayak so should i make a pr for this ui and then after that @rakshitkamboj can do the implementation of pushing the changes in profile to firebase and also the retreiving part from firebase ?
> 
> Let him complete the backend work first and then the UI can be changed, also let @avinashkranjan and @hareshnayak approve the UI first.

ok got it :)

**Comment by hareshnayak** [comment]
> > > yeah that's fine @HimeshNayak so should i make a pr for this ui and then after that @rakshitkamboj can do the implementation of pushing the changes in profile to firebase and also the retreiving part from firebase ?
> > 
> > 
> > Let him complete the backend work first and then the UI can be changed, also let @avinashkranjan and @hareshnayak approve the UI first.
> 
> ok got it :)

@anotherwebguy great work ! But as the app's current theme is dark, we can agree on the fact that it might not go with the app. I think for now we can have the same existing UI of the page.

**Comment by anotherwebguy** [comment]
> > > > yeah that's fine @HimeshNayak so should i make a pr for this ui and then after that @rakshitkamboj can do the implementation of pushing the changes in profile to firebase and also the retreiving part from firebase ?
> > > 
> > > 
> > > Let him complete the backend work first and then the UI can be changed, also let @avinashkranjan and @hareshnayak approve the UI first.
> > 
> > 
> > ok got it :)
> 
> @anotherwebguy great work ! But as the app's current theme is dark, we can agree on the fact that it might not go with the app. I think for now we can have the same existing UI of the page.

okay i understand but if u want we can also do this ui in dark theme @hareshnayak

**Comment by hareshnayak** [comment]
Even though your design is great, no doubt there, I think we should stick with the existing one for now 
Thanks for understanding @anotherwebguy

**Comment by anotherwebguy** [comment]
> Even though your design is great, no doubt there, I think we should stick with the existing one for now
> Thanks for understanding @anotherwebguy

okay
