### ISSUE TITLE
Adding Authentication feature in the app under SWoC 2021

### ISSUE THREAD

**Issue by Imadarshsri** [avinashkranjan/Friday#11]
The current version of the app does not have any authentication feature. I would like to work on this issue to add the authentication feature in the application. The idea is to build and design the Login and Signup page that will allow users to either signup or login to the app using Email id and Password or using Google Authenication.

**Comment by avinashkranjan** [comment]
@Imadarshsri Assigned to you..

**Comment by Imadarshsri** [comment]
Thanks...Add me to the Firebase Project for activating authentication services. My email id is: imadarshsri@gmail.com

**Comment by avinashkranjan** [comment]
Ohh Sure Sure.. Gimme a Sec.

**Comment by Imadarshsri** [comment]
Great...
