### ISSUE TITLE
Search bar focused border not set

### ISSUE THREAD

**Issue by abstrxtInfinity** [avinashkranjan/Friday#111]
Search bar enabled border not set, as shown in below image.
@avinashkranjan  I would like to fix it please assign this to me.
GSSOC'21 participant.
![bug](https://user-images.githubusercontent.com/55052738/111907291-abecd400-8a7a-11eb-8be3-ce86807d76e2.jpeg)

**Comment by avinashkranjan** [comment]
Go Ahead @abstrxtInfinity
