### ISSUE TITLE
Data is not fetched at first login

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#118]
**Describe the bug**
When the user logins for the first time in the app, the user data is not properly fetched and the default text is displayed.

**To Reproduce**
1. Clear data of the app.
2. Run the app on the emulator
3. Login with email and password
4. See Error: On Home Page It shows 'Hello Sir' rather than the name of the user and on profile page it shows loading...

**Expected behavior**
The data should be fetched properly as it is fetched when the app is restarted.

**Screenshots**
![Screenshot_20210325_122052](https://user-images.githubusercontent.com/30944790/112431514-a555a980-8d65-11eb-848c-b05816e955e3.png)
![Screenshot_20210325_122127](https://user-images.githubusercontent.com/30944790/112431523-a7b80380-8d65-11eb-9fd9-3ae358e01b15.png)
![Screenshot_20210325_122133](https://user-images.githubusercontent.com/30944790/112431530-a8e93080-8d65-11eb-8162-41bfde92d1a9.png)

**Additional context**
Anyone who wants to work on this issue under GSSOC21, kindly comment here and I will assign you the issue.

**Comment by D-Ajay-Kumar** [comment]
Any idea so far why it's happening?

**Comment by SamarpanCoder2002** [comment]
That happens some time due to lagging... I faced this problem in profile picture integration in other project.... When log-in at first, due to lagging, can't fetch data from firebase...but after reopen the app, it refresh and data come in picture

**Comment by D-Ajay-Kumar** [comment]
Aight lemme check the code for fetching data from firestore after logging in.

**Comment by SamarpanCoder2002** [comment]
> Aight lemme check the code for fetching data from firestore after logging in.

yah sure

**Comment by D-Ajay-Kumar** [comment]
@SamarpanCoder2002 bro can you update your local repo and run the app once? There seems to be some issues with the package versions not being compatible with each other. Especially the firebase ones. Can you please confirm whether it is global or just with me?

**Comment by D-Ajay-Kumar** [comment]
These are the ones that I am using currently that seem to work fine with each other. The ones in the master branch seem incompatible. @HimeshNayak could you also check please?

![vers](https://user-images.githubusercontent.com/56850266/112458368-b82aa700-8d82-11eb-8c94-ed4f841e4059.PNG)

**Comment by D-Ajay-Kumar** [comment]
The data is being fetched on the first login, this issue has been solved but the firebase storage package version isn't compatible with some other packages. After updating the package versions to the ones in the picture of the comment before this one I had to do some changes in code related to firebase storage. Is it alright if all that code is also included in this issue's solution?

**Comment by D-Ajay-Kumar** [comment]
The issue of data not being fetched has been solved but since older version of firebase storage was being used earlier, I had to refactor the code related to storage as well after updating the package versions. Is it alright if I commit those changes as well? Not a lot of changes, just a few lines of code had to be refactored.

**Comment by SamarpanCoder2002** [comment]
> The issue of data not being fetched has been solved but since older version of firebase storage was being used earlier, I had to refactor the code related to storage as well after updating the package versions. Is it alright if I commit those changes as well? Not a lot of changes, just a few lines of code had to be refactored.

Please go ahead bro @D-Ajay-Kumar .... @HimeshNayak please assign him to that issue

**Comment by HimeshNayak** [comment]
Assigning issue to @D-Ajay-Kumar
