### ISSUE TITLE
Add github action to auto label issues

### ISSUE THREAD

**Issue by muthuannamalai12** [avinashkranjan/Friday#120]
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21.

**Comment by avinashkranjan** [comment]
Go Ahead @muthuannamalai12

**Comment by pragati-kumar** [comment]
Hello @avinashkranjan. I'm a GSSOC'21 participant and I would really like to contribute to this issue.

**Comment by vaibhavihaveri** [comment]
Hello l am GSSOC 21  participant I like to work on this issue can u assign me.
