### ISSUE TITLE
Migrate the app to Null Safety

### ISSUE THREAD

**Issue by pawan2806** [avinashkranjan/Friday#124]
**Is your feature request related to a problem? Please describe.**
With null safety, you can reason about your code with more confidence. No more pesky runtime null dereferencing errors in deployed apps. Instead, you get static errors as you code. ~ dart officials

**Describe the solution you'd like**
[https://dart.dev/null-safety/migration-guide](url)

**Describe alternatives you've considered**

**Additional context**

**Comment by HimeshNayak** [comment]
Go Ahead @pawan2806. I'll assign this issue to you.

**Comment by HimeshNayak** [comment]
Any updates? @pawan2806

**Comment by thierryoliveira** [comment]
I felt free to make this migration and help the project with my contribution. The changes are in this pull request: #175
