### ISSUE TITLE
Add Constraint to Age Field in Signup

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#126]
**Describe the bug**
The Age Field in the signup form has a alphanumeric keyboard which needs to changed to a number keyboard so that the value is not null in the database. Also proper constraints are to be added and the validator message is to be changed

**Additional context**
Anyone willing to work on this issue under GSSOC21, then please comment here and I will assign you this issue.

**Comment by SamarpanCoder2002** [comment]
Can I work on it @HimeshNayak ...... I am also a GSSOC'21 particiapnt.... If I can forward with that....please assign me to here...Thanks @HimeshNayak @avinashkranjan

**Comment by HimeshNayak** [comment]
Sure, go ahead @SamarpanCoder2002 I'll assign it to you.

**Comment by SamarpanCoder2002** [comment]
> Sure, go ahead @SamarpanCoder2002 I'll assign it to you.

Thanks for assign @HimeshNayak ...I will made a pull request soon after my current pull request get merged(#125 ) ...... Hope you merge it soon @avinashkranjan

**Comment by SamarpanCoder2002** [comment]
Pull request added....hope you review it and merge it soon @HimeshNayak @avinashkranjan
