### ISSUE TITLE
After first Google/FB Sign-in, user navigate to the `log-in` page instead of `bottom_navigation` page

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#128]
**Is your feature request related to a problem? Please describe.**
If user First Time Sign-in with Google or Facebook, then user navigate to the `sign-up-additional page`...it's ok....But then they navigate to the log-in page.... That's not right I think.... In that two kinds of sign-in, after sign-up-additional details(at the time of first sign-in), user have to directly navigate to the `bottom_navigation` page instead of `log-in` page ..... I want to make it possible..

**Describe the solution you'd like**
After Google or FB sign-in, 
1. For first time, after `sign-up-form-additional-details`, user have to be navigate to the `bottom_navigation` page.......

For not first time, user directly navigate to `bottom_navigation` page after sign-in

**Describe alternatives you've considered**
According to above solution I described

**Additional context**
I am also a GSSOC'21 participant...If I can forward with that...please assign me to here....

Thanks @HimeshNayak @avinashkranjan

**Comment by avinashkranjan** [comment]
Assigned to you @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
@HimeshNayak @avinashkranjan .... I already make a pull request related to that...please take a look...Thank u....Hope you review it and merge it soon @avinashkranjan @HimeshNayak

**Comment by SamarpanCoder2002** [comment]
@avinashkranjan .... pull request reviewed successfully..Hope you merge it soon @avinashkranjan
