### ISSUE TITLE
List of Open Source programs in the Readme file

### ISSUE THREAD

**Issue by anirudhsai20** [avinashkranjan/Friday#131]
The Readme file can be enhanced by adding a list of all the Open Source programs in whcih this project has been listed in. Alos there are a lot of grammatical errors in the Readme file that needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @anirudhsai20
