### ISSUE TITLE
ERROR: Alerts Page (A RenderFlex Error)

### ISSUE THREAD

**Issue by mrmayurgithub** [avinashkranjan/Friday#132]
The content in the Alerts Page can't fit into a single page, so Renderflow error is being shown.

1. Go to 'Alerts Page'
2. See error

**Screenshots**
![delete](https://user-images.githubusercontent.com/58694295/113721569-456be500-970d-11eb-9f97-60e23a2ff91d.jpg)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 
**Smartphone (please complete the following information):**
 - Device: Redmi Note7s
 - OS: MIUI 12.0.2

**I am a GSSOC Participant and I would like to work on this simple issue**

**Comment by HimeshNayak** [comment]
@mrmayurgithub go ahead. I'll assign this issue to you.

**Comment by mrmayurgithub** [comment]
@HimeshNayak I've created a pull request.
