### ISSUE TITLE
FireStore can affected by Scammers

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#134]
**Is your feature request related to a problem? Please describe.**
In this app, If anybody signup(With Email and Password), details directly added to the firestore.... Now anybody can signup with some invalid email with that signup for scamming and pressure on firestore unnecessarily increases.

**Describe the solution you'd like**
For Signup(Email and Password Auth), after signup, user directly navigate to the log-in page.....After Email verification, is user login properly, check in the firestore that UID is present or not...If not, then user navigate to the `sign_up_additional` page and now data can store in firestore.... If yes, then user navigate to the bottom navigation page....

That can reduce the scammers activity effect on firestore....because, now If user log-in properly with email verification, then only data add to firestore...........Not at the time of sign-up as invalid email can use for signup

**Describe alternatives you've considered**
Described Above

**Additional context**
I am also a `GSSOC'21` participant.....If I can forward with that.....Please assign me to here....

Thanks @avinashkranjan @HimeshNayak

**Comment by avinashkranjan** [comment]
Go Ahead @SamarpanCoder2002
