### ISSUE TITLE
Wrong bottom navigation on login 

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#137]
**Describe the bug**
When the user is logged in after he/she had logged out from the profile page. The profile navigation button is active rather than home.

**To Reproduce**
1. Log out using log out button on profile page
2. Log in again

**Expected behavior**
The home navigation button should be active rather than profile

**Screenshots**
![image](https://user-images.githubusercontent.com/30944790/114031817-5ba6ac00-9899-11eb-8668-c6ac092bfdab.png)

**Additional context**
Any GSSOC'21 participant willing to work on this issue, please comment here and I'll assign it to you.

**Comment by Udit-singh** [comment]
@HimeshNayak I would like to work upon it.

**Comment by HimeshNayak** [comment]
Sure @Udit-singh, Go ahead!
