### ISSUE TITLE
ERROR: Homework Page (A RenderFlex Error)

### ISSUE THREAD

**Issue by mrmayurgithub** [avinashkranjan/Friday#139]
The content in the Recent HomeWork Page can't fit into a single page, so Renderflow error is being shown.

1. Go to 'Recent Homework'
2. See error
![deletetoo](https://user-images.githubusercontent.com/58694295/114069582-c5847d00-98bc-11eb-995c-ac3ff18d4549.jpeg)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 
**Smartphone (please complete the following information):**
 - Device: Realme 8 Pro

**I am a GSSOC Participant and I would like to work on this simple issue**

**Comment by oshi36** [comment]
Go ahead with this issue @mrmayurgithub

**Comment by mrmayurgithub** [comment]
@oshi36 I've created a PR for this issue.
