### ISSUE TITLE
Design: UI design of Login and Signup page #SWOC 2021

### ISSUE THREAD

**Issue by purnima143** [avinashkranjan/Friday#14]
The current app doesn't have a Login/Signup page. Below are a few designs, which are designed according to the current theme i.e. dark theme + purple color.

## Design 1
![Design1](https://user-images.githubusercontent.com/57852378/103857704-fc3fd100-50dc-11eb-932d-b75b460d123f.png)

## Design 2
![Design2](https://user-images.githubusercontent.com/57852378/103857715-02ce4880-50dd-11eb-8682-d07d6a9afa09.png)

##Design 3
![Design3](https://user-images.githubusercontent.com/57852378/103857727-095cc000-50dd-11eb-8bc1-47b26fcbdb4a.png)

**Comment by purnima143** [comment]
@avinashkranjan  please check the designs.

**Comment by avinashkranjan** [comment]
@purnima143 Great Work.. I love the First one. So we'll go with that design..
@Imadarshsri Check out the UI designs and Code accordingly..Go with **Design 1**

**Comment by Imadarshsri** [comment]
@avinashkranjan...okay I will get it done...

**Comment by avinashkranjan** [comment]
@all-contributors please add @purnima143  for design
