### ISSUE TITLE
Adding Light theme in the app

### ISSUE THREAD

**Issue by oshi36** [avinashkranjan/Friday#141]
Currently, the app is in a dark theme. Add few more themes for users. Some of my suggestions are light , velvet .

**Comment by Varun8216889** [comment]
Can, I take this issue??

**Comment by oshi36** [comment]
Hey @Varun8216889, can you please tell me about your approach that how will you do that?

**Comment by Varun8216889** [comment]
By adding some light and colour theme with the help of HTML and css.

**Comment by oshi36** [comment]
@Varun8216889 , currently this app is a mobile app and we are not working with flutter web .

**Comment by Ronak8602** [comment]
@oshi36  In profile page we can have toggle button with better UI which will switch themes into light and dark . We can provide 2 ThemeData functions which will be called using a ternary operator inside MaterialApp. Can i work on this issue.

**Comment by oshi36** [comment]
@Ronak8602 what is your status on this issue, are you working on it?

**Comment by chazuttu** [comment]
I will add a toggle button through which for shifting to dark & light mode. I have already worked on this issue , please assign this to me to make PR for the issue.

**Comment by oshi36** [comment]
Go ahead !! @chazuttu

**Comment by Samkit-shah** [comment]
If this issue solved?
If not can i work on it?

**Comment by avinashkranjan** [comment]
Go Ahead @Samkit-shah

**Comment by Samkit-shah** [comment]
> Go Ahead @Samkit-shah

Sure thank you .
