### ISSUE TITLE
Add Google Calendar

### ISSUE THREAD

**Issue by oshi36** [avinashkranjan/Friday#142]
Currently , app is using customizable calendar so instead of it use google calendar to enhance the functionality.

**Comment by nicks101** [comment]
Hey, can I work on it?

Also, can you tell a bit more about the issue?
It is integrating google calendar instead of the current one. Or make an option to add a reminder/event in google calendar by an api.

**Comment by oshi36** [comment]
Hi @nicks101 , It is about integrating the google calendar in the app as we have customize one.

**Comment by nicks101** [comment]
Okay I'll research on it and implement it.
