### ISSUE TITLE
Add Class Schedule Manually by the User

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#145]
**Is your feature request related to a problem? Please describe.**
Users Can Manually add Class Schedules to complete their task.... This is the extended version of #129 .....

**Describe the solution you'd like**
A segment of the app involves where the user can add a class schedule manually and that store in firestore with corresponding user data.....

**Describe alternatives you've considered**
Mentioned Above

**Additional context**
I am also a GSSOC21 participant... If I can forward with that.... Please assign me to here.....

Thanks @HimeshNayak @avinashkranjan

**Comment by HimeshNayak** [comment]
go ahead @SamarpanCoder2002, I'll assign this issue to you.

**Comment by SamarpanCoder2002** [comment]
> go ahead @SamarpanCoder2002, I'll assign this issue to you.

Thanks a lot

**Comment by SamarpanCoder2002** [comment]
@HimeshNayak @hareshnayak @avinashkranjan ..... I already made the request ..... Please review it and merge it .... Thanks

**Comment by SamarpanCoder2002** [comment]
Hello @HimeshNayak @avinashkranjan .... I fixed the bug in related pull request .... Please review and merge it..Thanks

**Comment by HimeshNayak** [comment]
> Hello @HimeshNayak @avinashkranjan .... I fixed the bug in related pull request .... Please review and merge it..Thanks @avinashkranjan @HimeshNayak

Done

**Comment by SamarpanCoder2002** [comment]
> > Hello @HimeshNayak @avinashkranjan .... I fixed the bug in related pull request .... Please review and merge it..Thanks @avinashkranjan @HimeshNayak
> 
> Done

Thanks a lot @HimeshNayak ... Hopw you merge it soon @avinashkranjan

**Comment by SamarpanCoder2002** [comment]
Hello @avinashkranjan ... I resolved the conflicts in the in this related pull request.... Please merge it as soon as possible before any conflicts raise again..... Otherwise, I have to manage code again and that really frustrating...

Hope you understand @HimeshNayak @avinashkranjan
