### ISSUE TITLE
Design Wireframe for Website

### ISSUE THREAD

**Issue by deeptea22** [avinashkranjan/Friday#147]
Hey, I would like to create the wireframe for the static website which would describe the app.
Please assign me this under GSSoC'21. Thank you :) @HimeshNayak @avinashkranjan

**Comment by oshi36** [comment]
Hey @deeptea22, Just let us know what will be your Plan of Action for this. I am assigning it to you.

**Comment by deeptea22** [comment]
@oshi36 I have already finished the wireframe. Please let me know how i should upload it? Is it as an image file? 
Also please assign me the design prototype issue as well #148 , so that i can continue with that. Thank you :)

**Comment by HimeshNayak** [comment]
Upload it as an image file... lets all discuss the wireframe and then we'll assign you #148 and you can work on it @deeptea22

**Comment by deeptea22** [comment]
@HimeshNayak okay sure 👍🏽 . This is what i've come up with for the wireframe : 
https://www.figma.com/file/xviuRdqrYnuZGrBBH5Rgrz/Untitled?node-id=0%3A1

**Comment by HimeshNayak** [comment]
> @HimeshNayak okay sure 👍🏽 . This is what i've come up with for the wireframe :
> https://www.figma.com/file/xviuRdqrYnuZGrBBH5Rgrz/Untitled?node-id=0%3A1

It looks great @deeptea22. @hareshnayak and @avinashkranjan kindly give your views on the UI

**Comment by oshi36** [comment]
@deeptea22 , the wireframe is great . Let's just know the reviews of @avinashkranjan then you can work on prototype.👍

**Comment by avinashkranjan** [comment]
Hey @deeptea22, Design Wireframe Looks Good..Kindly Create a PR on `gh-pages` 
Create a Folder Named **Design Wireframe**..
So, You can be marked for this Contribution..

**Comment by deeptea22** [comment]
Hey, @avinashkranjan I have added the wireframe in a folder named Design Wireframe and have made the PR on `gh-pages` branch. PR #151 Please have a look, Thank you :)
