### ISSUE TITLE
Overflow at signup page

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#155]
**Describe the bug**
Some pixels are overflowing at the sign up page

**Screenshots**
![Screenshot_20210415_234906](https://user-images.githubusercontent.com/30944790/114922451-4efdf700-9e49-11eb-9db5-cc3de6e82880.png)

**Solution**
Adjust the padding and margin of the widgets on the screen according to MediaQuery

**Additional context**
Anyone who wants to work on it under GSSOC may comment here.

**Comment by anotherwebguy** [comment]
i would like to work on this issue under gssoc ... plz assign me this issue @HimeshNayak

**Comment by HimeshNayak** [comment]
Sure, go ahead! @anotherwebguy !
