### ISSUE TITLE
Login Authentication/ Page /Panel

### ISSUE THREAD

**Issue by vatsalcode** [avinashkranjan/Friday#160]
**Try to build a login Panel/ Page. Where a person can login using Email/ Official id/Number.**
-The application looks more authentic when we have identity proof and using official email is a great way.
-UI/Design Should be attractive and matches the original theme of the application.

**Comment by avinashkranjan** [comment]
Hey @vatsalcode App Already Uses Google, Facebook and Email Auth What more are you suggesting?

**Comment by vatsalcode** [comment]
Hey, @avinashkranjan  we can also add the feature of mobile number opt login ??

**Comment by Ronak8602** [comment]
Hey @vatsalcode I have an idea to implement this
We can have a small underlined statement below Icons of google and Facebook telling 'login via mobile number'
on pressing that It would take us to a separate screen from where we can login through mobile number. on successfull OTP verification user gets logged in
@vatsalcode  Can I work on this issue
I am a GSSOC 2021 participant
If yes than please make me as a collaborator in Firebase Project
Email- ronakprajapati107@gmail.com

**Comment by avinashkranjan** [comment]
We Can,
We'll have a add a section in Sign Up Page for Phone No.
- We'll have to verify it

and We have a section of Login using phone 
- If you have registered using phone you'll need to feed the phone 
- and you'll get the otp to login...

If anyone is up for taking the issue, Assign them

**Comment by believeInJha** [comment]
@vatsalcode  I would like to work on this issue under GSSoc21!

**Comment by avinashkranjan** [comment]
Sure Go Ahead @believeInJha

**Comment by believeInJha** [comment]
Thanks for the opportunity @avinashkranjan, I will make the PR and submit it.

**Comment by believeInJha** [comment]
Hey @avinashkranjan, can you send me the firebase credentials?

**Comment by believeInJha** [comment]
`apurv.bmsit@gmail.com` is my firebase linked Gmail, kindly send me collaboration request.

**Comment by avinashkranjan** [comment]
@believeInJha Added you..

**Comment by believeInJha** [comment]
Hey @avinashkranjan, I have a doubt here, how are we gonna verify the mobile number is registered or not?

**Comment by believeInJha** [comment]
> Hey @avinashkranjan, I have a doubt here, how are we gonna verify the mobile number is registered or not?

@avinashkranjan, @vatsalcode, @HimeshNayak  can you please guide me into this cause, I'm really stuck at this part.

**Comment by HimeshNayak** [comment]
> > Hey @avinashkranjan, I have a doubt here, how are we gonna verify the mobile number is registered or not?
> 
> @avinashkranjan, @vatsalcode, @HimeshNayak can you please guide me into this cause, I'm really stuck at this part.

I guess that we can just check that the regex of the mobile number. if the number will be valid then the top will come to the phone.

**Comment by believeInJha** [comment]
@HimeshNayak No, I meant how to verify the number is registered/sign up before or not. cause then only we'll be able to log in the user with all their details.

**Comment by avinashkranjan** [comment]
Hey @pnkr01, It's not implemented, and you're free to take up this issue. Assigning it to you.

**Comment by pnkr01** [comment]
Thank you, I need the acess to firestore  to store the phone number and their corresponding data.

**Comment by avinashkranjan** [comment]
> pawankumar49871@gmail.com

Provided you access.

**Comment by pnkr01** [comment]
Hi, I have completed, and want to test and for that I have to change the security rules of firestore as I'm getting this issue(attached)
from

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}

to 

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}

![a](https://user-images.githubusercontent.com/83778936/178714837-41c3edcb-ea06-4f85-b200-02686dc2efd1.png)

**Comment by avinashkranjan** [comment]
> Hi, I have completed, and want to test and for that I have to change the security rules of firestore as I'm getting this issue(attached) from
> 
> rules_version = '2'; service cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read, write: if request.auth.uid != null; } } }
> 
> to
> 
> rules_version = '2'; service cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read, write: if true; } } }
> 
> Can I change the rule? ![a](https://user-images.githubusercontent.com/83778936/178714837-41c3edcb-ea06-4f85-b200-02686dc2efd1.png)

Go Ahead

**Comment by MihirCharan42** [comment]
hi could you assign this issue to me? I am a participant of GSSoC'2023 and would love to work on this issue

**Comment by avinashkranjan** [comment]
Sure Go Ahead @MihirCharan42

**Comment by LEARNER-dakshesh** [comment]
Can you please assign this issue as I have prior knowledge and I want to work on this.

**Comment by avinashkranjan** [comment]
Go Ahead @LEARNER-dakshesh

**Comment by andoriyaprashant** [comment]
Hey @avinashkranjan Please assign me this issue i am working on it 
Thank you
