### ISSUE TITLE
Faulty link in "CONTRIBUTING.md : Need more help?" section

### ISSUE THREAD

**Issue by Arsenic-ATG** [avinashkranjan/Friday#172]
In ["`Need more help?🤔`"](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md#need-more-help) section of ["CONTRIBUTING.md"](https://github.com/avinashkranjan/Friday/blob/master/CONTRIBUTING.md), The second link, according to the text, should redirect user to a place that gives information regarding "Cloning a repository" but rather takes us to 
> https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request

Which tells nothing about the process of cloning a repository. 

---

This looks like a typo as according to me, the link should rather redirect the user to the following:

> https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

**Comment by avinashkranjan** [comment]
Go Ahead @Dark-Knight11
