### ISSUE TITLE
Splash Screen for the App

### ISSUE THREAD

**Issue by Rajat119** [avinashkranjan/Friday#179]
**Splash Screen View**
-The application must contain a splash screen before the onboarding page so that the UI for the applocation will be on a boost and the onboarding page must be at least of 3 pages to give the overview.

**Comment by avinashkranjan** [comment]
- Hello @Rajat119 , Do you want to work on this issue?

**Comment by Rajat119** [comment]
Yeah sure

**Comment by avinashkranjan** [comment]
Go Ahead Assigning it to you. @Rajat119

**Comment by mmjsmohit** [comment]
Is this issue still open?

**Comment by Rajat119** [comment]
Yes I'm working in this, I'm busy with my exam lil bit that's why I'm taking time. It will be done

**Comment by Rizwan201** [comment]
Heyy @avinashkranjan i see this issue is still open can you assign this to me.

**Comment by Rizwan201** [comment]
@avinashkranjan the splash screen has been created and PR raised pls check
