### ISSUE TITLE
Adding Contributor Workflow to Documentation

### ISSUE THREAD

**Issue by Jiggy9** [avinashkranjan/Friday#182]
I am a contributor to GSSOC'23, an open-source project. I would like add a contributor workflow to the documentation. Could you please assign this issue to me? @avinashkranjan

**Comment by ashvaneetk** [comment]
@avinashkranjan I request your assignment of the issue involving the implementation of a Contributor Workflow in our documentation. I will commit required pull request as soon the issue get assigned.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by rafiya2003** [comment]
please assign this issue to me under GSSoC'23

**Comment by ombhojane** [comment]
Hey, I can understand the workflow and use case of this app. Along with this, Technical writing is the thing that interests me more. I would love to contribute in this issue for GSSOC 2023.

**Comment by harshsingh32** [comment]
I would like to improve the contribution.ndbof this project making it engaging for the users and make it more expressive, increase the engagement of this project. This motivate the users to contribute to the project and increase the project engagement.

**Comment by avinashkranjan** [comment]
Go Ahead @harshsingh32, Create an PR for the changes. will assiging the level depending upon the contribution.
