### ISSUE TITLE
Suggesting/Requesting for a logo refresh.

### ISSUE THREAD

**Issue by AnasNasim12** [avinashkranjan/Friday#183]
I believe the current logo is in need of a refresh. It is in need of an updated font and more attractive color scheme. Higher resolution assets are essential when it comes to scaling for bigger and more pixel-dense displays.

I would like to work on the logo if that's possible, I believe it to be beneficial for the application.

**Comment by Saksham0205** [comment]
I would like to make some changes in the Logo to make it more attractive.
Can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by avinashkranjan** [comment]
Issue Already Open #56
