### ISSUE TITLE
To update all dependencies and version of This Flutter project 

### ISSUE THREAD

**Issue by andoriyaprashant** [avinashkranjan/Friday#184]
Description - 
 
This Flutter project (Friday) is outdated, it is crucial to keep the project dependencies and version up to date to leverage the latest features, bug fixes, and improvements offered by the Flutter ecosystem and its associated packages.

To resolve this issue, the dependencies listed in the project's "pubspec.yaml" file need to be updated to their latest versions. 
And we also have to update build.gradle file for this 

**Prerequisites**
[-]  I am running the latest version
[-]  I checked the documentation and found no answer
[-]  I checked to make sure that this issue has not already been filed
[-]  I'm reporting the issue to the correct repository (for multi-repository projects)

1. Go to pubspec.yaml file and build.gradle file for check the version
2.  Click on terminal and type "flutter pub get" to know the updates before this we have to change the version of environment: sdk in 
    pubspec.yaml file 
4.  Scroll down to see the updates

**Expected behavior**
    Version up to date

**Screenshots**
![Screenshot 2023-05-20 211904](https://github.com/avinashkranjan/Friday/assets/121665385/adf43a26-d94d-4248-b8d9-3aba03865d05)

build.gradel -

![Screenshot 2023-05-20 231223](https://github.com/avinashkranjan/Friday/assets/121665385/8c6b697c-163b-4782-96d9-9a20b477f546)

**Comment by andoriyaprashant** [comment]
I already working on this issue

**Comment by andoriyaprashant** [comment]
Hey @avinashkranjan Please review my Pull request #185 
Thank you

**Comment by aniket2125ec1117** [comment]
I want to work on this issue i have recently worked on this issue.

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by TRISHAHALDER** [comment]
I want to do this.

**Comment by AnushkaKalra** [comment]
HI @andoriyaprashant 
Please let me know if I can work on this issue. Would really like to be assigned to it as a part of GSSoC'23

**Comment by TRISHAHALDER** [comment]
Sure, I want to contribute as a part of gssoc

**Comment by ombhojane** [comment]
Hey, I'm Om, I'm aware of this issue as it happened to me. Can you please assign this issue to me, I really want to contribute in this
