### ISSUE TITLE
Adding more graphics 

### ISSUE THREAD

**Issue by Agarwalvidu** [avinashkranjan/Friday#186]
If we can add more graphics in the project it will make the project more likable by the users. For example we can add some sliders on the top of our homepage. And also we can create a movable logo. 

Animations will help us to look and feel our Friday cool.
I want to contribute in this project as a GSSOC contributor.

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by TRISHAHALDER** [comment]
can you please assign me this issue under GSSoc 2023. I already worked on animation before hand

**Comment by MUDITJAIN2** [comment]
I want to work on this as a part of GSSoC'23, could you please assign it to me?

**Comment by Apreksha** [comment]
Hello @avinashkranjan. I'm a GSSoCC'23 contributor. I would like to add more graphics. Could you please assign this task to me.

**Comment by avinashkranjan** [comment]
Go Ahead @Saksham0205, Assigning it to you.

**Comment by Agarwalvidu** [comment]
Sir I want to get assigned for this task . I have some great ideas I can show using Figma. I eagerly want to work on this project.
