### ISSUE TITLE
Add better color Scheme for UI 

### ISSUE THREAD

**Issue by Abhinavcode13** [avinashkranjan/Friday#188]
please Assign this issue to me under gssoc 23 @avinashkranjan

**Comment by MUDITJAIN2** [comment]
Please assign this issue to me.

**Comment by Apreksha** [comment]
Hello @avinashkranjan. I'm a GSSoCC'23 contributor. I would like to add better colour scheme to the UI. Could you please assign this task to me.

**Comment by avinashkranjan** [comment]
Go Ahead @Abhinavcode13

**Comment by Abhinavcode13** [comment]
hello there where can I find the color scheme for the app , like in which file @avinashkranjan

**Comment by avinashkranjan** [comment]
We don't already have an color scheme as such, if you want you can create a new Color Scheme.

**Comment by Abhinavcode13** [comment]
can i do that so ? @avinashkranjan

**Comment by Abhinavcode13** [comment]
@avinashkranjan ??
