### ISSUE TITLE
Navbar required 

### ISSUE THREAD

**Issue by Abhinavcode13** [avinashkranjan/Friday#190]
Adding test schedule , timetable, student login in the navbar , please assign this issue to me @avinashkranjan

**Comment by MUDITJAIN2** [comment]
Please assign this issue to me.

**Comment by Apreksha** [comment]
Hello @avinashkranjan. I'm a GSSoCC'23 contributor. I would like to add the feature of Navbar. Could you please assign this task to me.

**Comment by avinashkranjan** [comment]
Go Ahead @Abhinavcode13, Assigning it you

**Comment by ShubhangiiMishRa** [comment]
Hey, please assign me this issue

**Comment by avinashkranjan** [comment]
Any Updates on this @Abhinavcode13

**Comment by Tushar924738305063** [comment]
Please assign me this issue would like to add navigation bar having hover effects and will customize as per requirement

**Comment by Chavisn** [comment]
@avinashkranjan I want to work on this issue. kindly assign me this.

**Comment by Abhinavcode13** [comment]
You can assign it to @Chavisn

**Comment by avinashkranjan** [comment]
Go Ahead @Chavisn

**Comment by Drishtianand19** [comment]
@avinashkranjan Please assign this issue to me, would love to work on it

**Comment by LEARNER-dakshesh** [comment]
Hello All,I would like to work on this issue.Can you give me a chance to work on it.

**Comment by alam-shoaib** [comment]
can i work on this issue?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @alam-shoaib

**Comment by alam-shoaib** [comment]
@avinashkranjan  can please give me brief description of what is to be to be like which page should o add the  navBar

**Comment by chinmaywali** [comment]
can i work on this..!???

**Comment by VOLTAR99** [comment]
I would like customize the Nav bar, assign me please
