### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [avinashkranjan/Friday#192]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by avinashkranjan** [comment]
Hello @harshsingh32, What are the changes that you're suggesting.. will assign then

**Comment by harshsingh32** [comment]
I would like to improve the readme file of this project using catchy phrases and expressive information about the project, increase the engagement of this project making it more expressive. This motivate the users to contribute to the project and collaborate with community.

**Comment by avinashkranjan** [comment]
Create an PR, Then will have a look and assign the level

**Comment by PravanshuSamadhiya** [comment]
I want to add the Steps in Read.Me file for " How To Contribute in this Project " For Beginners

**Comment by avinashkranjan** [comment]
No, We Already have an `Contribution.md` why to add an section for ` How To Contribute in this Project ` ?
