### ISSUE TITLE
I Want to Create a Document of "How to Contribute in this Project" For Beginners 

### ISSUE THREAD

**Issue by PravanshuSamadhiya** [avinashkranjan/Friday#196]

**Comment by PravanshuSamadhiya** [comment]
Assign this Issue to me I will Write the Steps for Beginners "How to Contribute in this Project"?

**Comment by Khushal747** [comment]
I would like to work in this issue under GSSOC'23 ,please assign me this issue.

**Comment by avinashkranjan** [comment]
Issue already Fixed in the PR #197, 

Duplicate Issue Closing this issue
