### ISSUE TITLE
 Error in CircleAvatar Widget 

### ISSUE THREAD

**Issue by andoriyaprashant** [avinashkranjan/Friday#198]
**Describe the bug**
 Error in CircleAvatar Widget (header.dart) 

**Prerequisites**
[-] I am running the latest version
[-] I checked the documentation and found no answer
[-] I checked to make sure that this issue has not already been filed
[-] I'm reporting the issue to the correct repository (for multi-repository projects)

**To Reproduce**
1. Go to 'lib\header.dart'
2. Scroll down
3. Click on 'CircleAvatar Widget'

**Expected behavior**
With no error in Widget

**Screenshots**

![Screenshot 2023-05-23 225825](https://github.com/avinashkranjan/Friday/assets/121665385/8cf712b0-feba-4468-8a3d-6e3df900a573)

**Comment by andoriyaprashant** [comment]
hello @avinashkranjan 
I have already started working on the issue

**Comment by andoriyaprashant** [comment]
Hey @avinashkranjan Please review my pull request #199 
Thank you

**Comment by avinashkranjan** [comment]
Assigned @andoriyaprashant
