### ISSUE TITLE
Scrollable Bug in Homepage

### ISSUE THREAD

**Issue by infiniteoverflow** [avinashkranjan/Friday#2]
When we scroll down on the homepage , the Recent Alerts and Recent Homework section acts like a scrollable widget and due to that the main scrolling is not accessible.

**Solution :**  Setting the attribute `physics :` of the ListView to `NeverScrollableScrollPhysics` will make sure the inner ListView is not scrollable and takes up the space required by the inner ListView.

The following video can give you a clear insight of the bug : 

https://user-images.githubusercontent.com/40236624/103156185-38655e80-47cc-11eb-937e-ae30cb257e14.mov

**Comment by avinashkranjan** [comment]
Assigned to you @infiniteoverflow You can go ahead with the fix.
