### ISSUE TITLE
[GSSoC'23] Improve the project image dashboard in the Readme file

### ISSUE THREAD

**Issue by anandanmukh** [avinashkranjan/Friday#200]
**Is your feature request related to a problem? Please describe.**
The app screenshots look very plain and basic. We need to make it more presentable. I just want to make it seem more appealing for anyone visiting the project

**Describe the solution you'd like**
- I would take the images from the Friday/graphics folder and add a frame to it, and finally add it to a poster. Doing this, will make the readers feel like they are holding the app in their hands
- I would choose the colour of the background in accordance with the design theme
**Additional context**
@avinashkranjan  Please assign this to me under the GSSoC'23. 
### I have added some examples of how this project could look like (from my own repo)
![flutter_projects_1](https://github.com/avinashkranjan/Friday/assets/67072228/5187cd02-6593-44b3-9ecf-f7b9da5c7d5a)

**Comment by avinashkranjan** [comment]
Go Ahead @anandanmukh
