### ISSUE TITLE
[GSSOC23]Adding onboarding for new users

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#201]
**Is your feature request related to a problem? Please describe.**
The app doesn't have a proper onboarding set up. If done, it would make the users get familiar with the application fairly easily and would make them understand how to use the application properly. 

**Describe the solution you'd like**
I'd design and implement the intro screens along with proper onboarding, so that when the app would be installed and opened for the first time, the users would be greeted by an automated experience which would acquaint users with app's features and how to use it. 

**Sample intro and onboarding screens for the purpose of understanding and clarity**
![](https://uplandsoftware.com/localytics/wp-content/uploads/sites/45/2020/06/app-user-onboarding.png)
![](https://www.datocms-assets.com/48294/1660898686-mad-onboarding-9-impact.png?auto=format)

**Comment by Salman313ali** [comment]
i can contribute  to this project, as i was recently working on UI/ UX fronted design using Flutter, Assign me this issue so i can contribute under the label of GSSOC

**Comment by Amna-Yasir** [comment]
I want to contribute under the label Of GSSOC

**Comment by ShubhangiiMishRa** [comment]
Hey, please assign me this issue

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh

**Comment by jaivsh** [comment]
Hi @avinashkranjan 
I've completed the PR work and have created a pull request regarding the same. Can you please check the work?
Thanking you in anticipation!
