### ISSUE TITLE
Design: Homepage UI design #SWoC 2021

### ISSUE THREAD

**Issue by purnima143** [avinashkranjan/Friday#21]
Below is the design of the homepage.
## Homepage design
![homepage](https://user-images.githubusercontent.com/57852378/104084109-9f722100-526a-11eb-8dc6-6bf09728c779.png)
## Overall design along with login and signup page
![friday](https://user-images.githubusercontent.com/57852378/104084111-a1d47b00-526a-11eb-8ff0-832f4c4f1fdb.png)

**Comment by avinashkranjan** [comment]
Change `you won't miss another assignment deadline or any upcoming test.` to `Your Personal Classroom Assistant` Rest It's Great...
Great Job..

**Comment by purnima143** [comment]
With modification
![homepage-friday](https://user-images.githubusercontent.com/57852378/104084378-8c605080-526c-11eb-8520-81cace2d2f25.png)

**Comment by avinashkranjan** [comment]
Assigning it to you @Imadarshsri
