### ISSUE TITLE
Add hovering effect on the blogs of recent alerts and homeworks.

### ISSUE THREAD

**Issue by uniiquecornnx** [avinashkranjan/Friday#210]
I'm from GSSoC'23

**Is your feature request related to a problem? Please describe.**
It would make the app even more engaging and attractive if we add a hovering effect to different alerts when clicked on them to  target the correct blog

**Describe the solution you'd like**
Hovering effect

**Comment by jaichiranjeeva** [comment]
You're working on this ? If not , I Would contribute for this issue

**Comment by Drishtianand19** [comment]
@avinashkranjan please assign me this issue

**Comment by avinashkranjan** [comment]
Go Ahead

**Comment by Dev-anshika98** [comment]
@avinashkranjan ...If this issue is open ..can you please assign this to me under the tag gssoc'24
