### ISSUE TITLE
Feature : Collaboration and Study Groups

### ISSUE THREAD

**Issue by Pratik-11** [avinashkranjan/Friday#218]
**Is your feature request related to a problem? Please describe.**
A major problem while doing some group project, assignment and everything is to make a whatsapp group everytime which can have all the nessesary people we need in it with all the materials in the group at a place.

**Describe the solution you'd like**
A solution to that would be study groups or collaboration system in the app when we add some assignment we can add collaborators in it which can edit and upload stuff. also with a built in chat for support and discussion

**Describe alternatives you've considered**
The chat part can be complex as of now for starting we can consider the collaborator feature like for example if one assignment is a group work so all collaborators can have like permissions of view or edit like that

**Comment by avinashkranjan** [comment]
Go Ahead @Pratik-11

**Comment by andoriyaprashant** [comment]
Please assign me this @avinashkranjan 
I have already started working on it, and I will soon open a pull request for it.
Thank you

**Comment by andoriyaprashant** [comment]
Hey @avinashkranjan Please review my pull request @avinashkranjan 
Thank you
