### ISSUE TITLE
 Error : auth_input_form_field.dart file

### ISSUE THREAD

**Issue by andoriyaprashant** [avinashkranjan/Friday#219]
**Describe the bug**
The auth_input_form_field.dart file in the previous code had a few issues that needed to be fixed.
(Friday\lib\widgets\auth_input_form_field.dart)

**Prerequisites**

-  I am running the latest version
-  I checked the documentation and found no answer
-  I checked to make sure that this issue has not already been filed
-  I'm reporting the issue to the correct repository (for multi-repository projects)

**To Reproduce**
1. Go to friday repo 
2. Click on lib\widgets\auth_input_form_field.dart
3. See error

**Expected behavior**
File with no error and clean code

**Comment by avinashkranjan** [comment]
Go Ahead @andoriyaprashant
