### ISSUE TITLE
Readme.md misplaced elements 

### ISSUE THREAD

**Issue by Pratik-11** [avinashkranjan/Friday#225]
**Describe the bug**
presentation error in readme.md

**Screenshots**

![GitHub - avinashkranjan_Friday_ 🎓 Friday - Your Personal Class Manager Assistant, It'll never let you miss another assignment deadline or upcoming test  - Brave 5_30_2023 5_27_52 PM](https://github.com/avinashkranjan/Friday/assets/72139212/cc9f6aca-d162-49a3-8c63-56de5edf225e)

**Expected behavior**
The text misplaced "Opinion " will be placed up at its place also the logo will be set to middle

**Additional context**
Beginner level documentation bug

**Comment by avinashkranjan** [comment]
Already Updated
