### ISSUE TITLE
Create Issue Forms

### ISSUE THREAD

**Issue by dakshsinghrathore** [avinashkranjan/Friday#263]
**Describe the bug**
Currently, the issue template for this repo seems to be basic also it is less visually appealing.👇

Currently 

![Screenshot 2023-06-11 at 01-11-35 New Issue · MonalikaPatnaik_UMatter](https://github.com/MonalikaPatnaik/UMatter/assets/115932772/ffffaa50-11cd-44f8-b5f2-b45e0e712ec9)

Changes I will make 

![Screenshot 2023-06-11 at 01-12-48 New Issue · dakshsinghrathore_htmltut](https://github.com/MonalikaPatnaik/UMatter/assets/115932772/24e42af3-1b4f-4d75-9f29-805e50d63fd5)

**Prerequisites**
Please go through the following questions for yourself before submitting an issue. 

-  I am running the latest version
-  I checked the documentation and found no answer
-  I checked to make sure that this issue has not already been filed
-  I'm reporting the issue to the correct repository (for multi-repository projects)

**To Reproduce**

**Expected behavior**
A clear and concise description of what behaviour were you expecting.

**Screenshots**

**Please provide the relevant information about your setup**
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
**Will add issue forms to the respective issues to make it easier for the contributor to raise it.**
Here is an example of how a ***Bug Issue Form*** will look like 👇

![Screenshot 2023-06-11 at 01-15-06 New Issue · dakshsinghrathore_htmltut](https://github.com/MonalikaPatnaik/UMatter/assets/115932772/d6d11ddf-3874-4229-b9a8-6087c99e10e2)

**Kindly Assign this issue to me**

**Comment by andoriyaprashant** [comment]
Hello @avinashkranjan 
I noticed this issue is still open. Can I take it up? If yes, could you please assign it to me? I would love to contribute and help resolve it.
Thank you
