### ISSUE TITLE
Addition of dependabot.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [avinashkranjan/Friday#272]
We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.

@avinashkranjan  please assign me this issue under gssoc'23.

**Comment by Drishtianand19** [comment]
We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.

@avinashkranjan please assign me this issue under gssoc'23.

**Comment by avinashkranjan** [comment]
Go Ahead @DivyanshiNarang
