### ISSUE TITLE
Alert box's theme to add new college doesnt match with app's theme.

### ISSUE THREAD

**Issue by Imsurajr** [avinashkranjan/Friday#285]
**Is your feature request related to a problem? Please describe.**
While Signing up, I found that my college was not listed in the given list, and when the alert box showed up to add new college, It didn't matched with the dark background and it flashed, seemed pretty odd.

**Describe the solution you'd like**
If the alert box's theme matches that of the apps, it will improve user experience. My suggestion is to update this alert dialog's colour and its content to match the app's theme.

**Describe alternatives you've considered**
Just changing the colour of alert box will work for this issue.

**Additional context**
Screenshots to refer 

![WhatsApp Image 2023-06-20 at 15 02 46hh](https://github.com/avinashkranjan/Friday/assets/92632170/cbdb6f6f-b8b3-4672-8bf7-c78b51671a19)

I can fix this issue , please assign this issue to me @avinashkranjan .

**Comment by avinashkranjan** [comment]
Go Ahead @Imsurajr

**Comment by Imsurajr** [comment]
Please assign the issue to me as well.
