### ISSUE TITLE
Feat:Dockerize project

### ISSUE THREAD

**Issue by shraddha761** [avinashkranjan/Friday#316]
### Describe the feature

Create a docker file for project which help to you to package your application and its dependencies into a container, making it highly portable. The Docker image can be run on any system that supports Docker, ensuring consistent behavior across different environments. It allow you define the exact steps needed to build your application environment. By versioning your Dockerfile, you can reproduce the exact same environment at any point in the future. This helps avoid "it works on my machine" issues and facilitates collaboration among team members.

### Add ScreenShots

Docker file for project

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @shraddha761
