### ISSUE TITLE
BUG: Error in signup_forms_additional_details.dart leading to app crash

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

During my signup process, post logging in, when I was directed to additional details screen(signup_forms_additional_details.dart), the application crashes. 

I'd like to fix this isue. Please assign this to me under GSSOC 23'. 

### Add ScreenShots

![Screenshot_20230704_002216](https://github.com/avinashkranjan/Friday/assets/93859359/82b4499f-bc3f-4cfe-9092-263ffa6d78ab)

<img width="1470" alt="Screenshot 2023-07-04 at 12 26 31 AM" src="https://github.com/avinashkranjan/Friday/assets/93859359/21c2ceb8-228f-483f-967e-459455473e6e">

### What browser are you seeing the problem on?

Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
Hey @HimeshNayak, please assign to me this issue.

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh

**Comment by jaivsh** [comment]
Hi @avinashkranjan can you please review this PR?
