### ISSUE TITLE
BUG: README.md file 

### ISSUE THREAD

**Issue by andoriyaprashant** [avinashkranjan/Friday#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It is necessary to improve the readme file.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by suman-somu** [comment]
"How to Contribute" section can also be improved in the similar way. Maybe you should add that too in the PR.

**Comment by andoriyaprashant** [comment]
@suman-somu No, I don't think so because the changes I made were necessary, specifically for the parts that required them. However, there is no need for changes in the 'how to contribute' file.

**Comment by suman-somu** [comment]
These are your changes, and 
![image](https://github.com/avinashkranjan/Friday/assets/75962762/2fece859-64dd-4631-8eb6-c8279f1eee23)
You can make the code to a new line like you did above
![image](https://github.com/avinashkranjan/Friday/assets/75962762/2428560f-1a28-4f0d-b4ef-4d7e83170beb)

**Comment by andoriyaprashant** [comment]
@suman-somu Thank you for your suggestion 👍
