### ISSUE TITLE
Feat: Adding a Share app feature

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#336]
### Describe the feature

I'd add a share app feature in the profile section, through which the users would be able to share the application using the share intent. The share intent would search for all aviliable platforms aviliable on device, where the share process can be completed. 

### Add ScreenShots

![](https://user-images.githubusercontent.com/93859359/252431575-12338bc7-c56e-4184-a688-18d480773aa1.png)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
Hi @avinashkranjan can u please assign to me this issue?

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh
