### ISSUE TITLE
Feat: Adding a settings seection with basic settings for the project

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#340]
### Describe the feature

I'd add a "settings" section for the project, where the users can go through in order to change the settings associated with the project. I'd also add a few setting options, like adding a "dark mode", and a response/feedback tab for users. 

### Add ScreenShots

Sample screenshot for reference and understanding purpose: 

![image](https://github.com/avinashkranjan/Friday/assets/93859359/c8f726d1-ca6a-456d-8e27-5c2b5672f6d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by jaivsh** [comment]
Hi @avinashkranjan can u please assign to me this issue?

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh

**Comment by andoriyaprashant** [comment]
Hey @avinashkranjan I had already worked on this issue earlier and had opened a pull request for it, which you have already merged #318  However, you only added a level 2 label to it :(

**Comment by avinashkranjan** [comment]
Updated @andoriyaprashant

**Comment by jaivsh** [comment]
@avinashkranjan can u please guide me where the heck is the ```settings section``` really inside the app? I've just updated and pulled to the latest version. However, Im unable to find a proper settings section anywhere in the application even after scanning every bit of the app. So please see to it. I cant find the implementation done in #318 anywhere in the application for whatever reasons. You should ask @andoriyaprashant where the heck is the implementation really in the application.
