### ISSUE TITLE
Feature: Theme Feature in settings 

### ISSUE THREAD

**Issue by andoriyaprashant** [avinashkranjan/Friday#346]
### Describe the feature

The theme feature in a Flutter app allows users to personalize the appearance of the app by choosing between different themes, such as light and dark themes. Themes define the visual style of various UI elements like buttons, text, backgrounds, and more.

### Add ScreenShots

NA 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by raman04-byte** [comment]
Can I work on this feature?
