### ISSUE TITLE
Feat: Updating the UI of "help" section in accordance with the app's base UI.

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#354]
### Describe the feature

```The Help section currenty has a very basic and simplistic UI, which is out of league with the application's current UI. I'd update the base UI of the help section page, including the "Contact Us" page as well as the "App Info" page, so that they become in-sync with the rest of the application. ```

### Add ScreenShots

![Screenshot_20230721_141555](https://github.com/avinashkranjan/Friday/assets/93859359/77d317aa-7ed8-4408-b35b-d96ebb845b52)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh
