### ISSUE TITLE
Feat: Updating "Contact Us" page and adding an API for the "Contact Us" button to work.

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#355]
### Describe the feature

I'd implement a google sheet where the user's contact us queries would be stored when they would be submitted from the application. The google sheet would be accessable via a RESTful API which I'd create in order to connect it with the application and send the user's queries through this API. I'd also create new blocks in the same page, which would include:

- an ```email``` block, for taking the user's email
- a ```timestamp```, for taking the timestamp of the query.
- a ```name``` block, for taking the user's name. 

### Add ScreenShots

<img width="1470" alt="Screenshot 2023-07-21 at 2 27 26 PM" src="https://github.com/avinashkranjan/Friday/assets/93859359/4bcb5a25-7989-4382-89f9-669dad19fbd4">

![Screenshot_20230721_142639](https://github.com/avinashkranjan/Friday/assets/93859359/037d56d9-c3b9-4fa2-a95e-14ddde685db7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh
