### ISSUE TITLE
Feat: Updating the UI of the "FAQ section"

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#356]
### Describe the feature

The "FAQ" section currently has a very basic UI which is out of phase with the rest of the application's UI style and architecture. I'd update the "FAQ" section's UI in such that it becomes in-sync with the rest of the UI. 

### Add ScreenShots

![Screenshot_20230721_141610](https://github.com/avinashkranjan/Friday/assets/93859359/27d9aa2f-63b2-4fb2-a9f9-25c6b8f84788)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh
