### ISSUE TITLE
Feat: Adding new Settings options in the settings section. 

### ISSUE THREAD

**Issue by jaivsh** [avinashkranjan/Friday#357]
### Describe the feature

The "Settings" section currently has only 4 basic settings. I'd add more setting options to the application, which includes the following: 
- ```Light mode/Dark mode switch```: Through this, the app's light and dark mode background and primary colors can be adjusted. 
- ```Notifications```: Through this, the users would be able to select weather they want to turn on the app's notifications or not. 

### Add ScreenShots

![Screenshot_20230720_163155](https://github.com/avinashkranjan/Friday/assets/93859359/6675fde3-fff2-4fd4-8fc7-e8577ff903e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Go Ahead @jaivsh
