### ISSUE TITLE
Animating the Navbar

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Friday#37]
# AIM
- The main purpose is the animate the navbar. So, It looks more user friendly and interactive.

# Details
- You can choose for multiple types of animation and select and code which suites the best. 
- Before you choose one and start working. Send a gif in this Issue showing what would that look like.

**Comment by Imadarshsri** [comment]
I can do this. I will let you know about the animation which we could use for the NavBar.

**Comment by avinashkranjan** [comment]
Sure @Imadarshsri Go ahead.... Assigning it to you..

**Comment by Imadarshsri** [comment]
Hey, sorry for the late info, I am working on implementing this animated navigation bar.

![navBarAnimation1](https://user-images.githubusercontent.com/45717875/104886279-7a2e9280-598f-11eb-90c8-3ec9a46e3115.gif)

Here, instead of this particular color schema, I am using our app's theme colors

**Comment by avinashkranjan** [comment]
@Imadarshsri ..This Looks Good, But I don't think there's enough space in the navbar to implement this..

**Comment by Imadarshsri** [comment]
yeah, I will try to implement this as minimal as possible.

**Comment by avinashkranjan** [comment]
> yeah, I will try to implement this as minimal as possible.

Okay Then Go ahead..
