### ISSUE TITLE
Adding new Homeworks and Classes under SWoC 2021

### ISSUE THREAD

**Issue by Sarthak-9** [avinashkranjan/Friday#4]
The idea of this app looks interesting. But as I can see that the homework and classes are hard coded. So I can work on a method to add new homeworks and classes to this list. I will add beautifully designed pages for adding these. May I go ahead with this under Script Winter of Code 2021. I have ideas of adding various other features also to this app.

**Comment by avinashkranjan** [comment]
Sure @Sarthak-9 Go ahead....
Just Change the Issue heading to SWoC 2021.. Assigned to Issue to you..

**Comment by Sarthak-9** [comment]
Sure. Thanks

**Comment by Siddhant-K-code** [comment]
Idea: can we try to scrap google classrooms, Microsoft Teams Assignment to the list.
implementation is hard, but we can give it a try.

**Comment by avinashkranjan** [comment]
You can go ahead with the implementation @Siddhant-K-code

**Comment by avinashkranjan** [comment]
Any updated @Siddhant-K-code @Sarthak-9 You guys need some ideas implementing it?

**Comment by Sarthak-9** [comment]
I am working on it but we can have a discussion

**Comment by nicks101** [comment]
If no one's working on it, can it be assigned to me?

**Comment by avinashkranjan** [comment]
Go Ahead @nicks101

**Comment by nicks101** [comment]
I'm getting this error while signing up.

```
W/Firestore(19601): (22.0.1) [WriteStream]: (1f14cc8) Stream closed with status: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}.
W/Firestore(19601): (22.0.1) [Firestore]: Write failed at users/2bzMUe59MwMGRvR2raJMFInOfvh1: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
E/flutter (19601): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
E/flutter (19601): #0      MethodChannelDocumentReference.set
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:43
E/flutter (19601): <asynchronous suspension>
E/flutter (19601): #1      DocumentReference.set
package:cloud_firestore/src/document_reference.dart:78
E/flutter (19601): #2      UserDBServices.addUser
package:class_manager/services/user_db_services.dart:19
E/flutter (19601): #3      UserInfoServices.addUserToDatabase
package:class_manager/services/user_info_services.dart:21
E/flutter (19601): #4      _SignUpFormAdditionalDetailsState.build.<anonymous closure>
package:class_manager/widgets/signup_form_additional_details.dart:215
E/flutter (19601): #5      _SignUpFormAdditionalDetailsState.build.<anonymous closure>
package:class_manager/widgets/signup_form_additional_details.dart:195
E/flutter (19601): #6      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:993
E/flutter (19601): #7      _InkResponseState.build.<anonymous closure>
package:flutter/…/material/ink_well.dart:1111
E/flutter (19601): #8      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:183
E/flutter (19601): #9      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:598
E/flutter (19601): #10     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:287
E/flutter (19601): #11     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:259
E/flutter (19601): #12     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
E/flutter (19601): #13     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:362
E/flutter (19601): #14     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:338
E/flutter (19601): #15     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:267
E/flutter (19601): #16     GestureBinding._handlePointerEvent
package:flutter/…/gestures/binding.dart:295
E/flutter (19601): #17     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:240
E/flutter (19601): #18     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:213
E/flutter (19601): #19     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (19601): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (19601): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (19601): #22     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (19601): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

```

The emulator I'm running on: `AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)`

Below are the screenshots of the emulator stuck on the sign-up screen.

![Screenshot_1615394617](https://user-images.githubusercontent.com/32807816/110665024-fa35e380-81ed-11eb-8013-3890724a15bb.png)
![Screenshot_1615394620](https://user-images.githubusercontent.com/32807816/110665031-fb671080-81ed-11eb-870e-3a856e08a641.png)

Can you please guide me on this?

**Comment by avinashkranjan** [comment]
@nicks101 Lemme check on my device once..Will get back to you in a giffy.

**Comment by avinashkranjan** [comment]
hey @nicks101 There seems to be some issue with signup process..It's not re-directing to home page after signing up..
I'll fix the bug soon for the time being you can do this: After you've created you email and password and it's stuck on signup page..exit the app clear storage and then login with the created credentials you'll be logged into the app..

**Comment by nicks101** [comment]
> hey @nicks101 There seems to be some issue with signup process..It's not re-directing to home page after signing up..
> I'll fix the bug soon for the time being you can do this: After you've created you email and password and it's stuck on signup page..exit the app clear storage and then login with the created credentials you'll be logged into the app..

okay.

**Comment by nicks101** [comment]
hey @avinashkranjan , can you give me the template for firestore cloud? Mainly the path to classes document of a student.

Also, I wanted to clarify the below points : 

1. Only dummy data (either from firebase or hardcoded in-app) is being displayed on every screen. This is because there is no option to add any data (other than user info while signing up) maybe.
2. Some of the screens (recent tab, profile tab) are showing CircularProcessIndicator widget only. And a firebase permission error in the console.
3. What I propose to do in this issue's PR -> Fetch classes from firestore and display them. Add a button to add classes. Edit any class.

**Comment by nicks101** [comment]
hey @avinashkranjan , I've added dummy data on firestore, and classes displayed on the app are being fetched from there.
I was wondering if there is any UI mock for adding a class, I'll implement that as well.
Or should I open a pull request with current changes only?

**Comment by avinashkranjan** [comment]
Hey @nicks101 Will send you the UI in few hours...You can implement it then..

**Comment by nicks101** [comment]
Updates on the issue : 

- Dummy data added on firestore  : `colleges -> USICT-BTECH-CSE-3 -> classes`
- Fetching and displaying firestore data (classes) in the app.

Let me know the next steps, please.

**Comment by HimeshNayak** [comment]
I have seen that you have added the classes in the firestore. Please write a function to read the data from firestore and display it for the required college. You can view the similar function for homework for reference.
@nicks101

**Comment by nicks101** [comment]
> I have seen that you have added the classes in the firestore. Please write a function to read the data from firestore and display it for the required college. You can view the similar function for homework for reference.
> @nicks101 

Hey @HimeshNayak, this part is done.
I'm fetching classes data from firestore and displaying them.
I can't fetch for a particular college yet as we have reference ID for a collage right now. It's all dummy data.
Should I open a PR so you can see the changes?

**Comment by nicks101** [comment]
> > I have seen that you have added the classes in the firestore. Please write a function to read the data from firestore and display it for the required college. You can view the similar function for homework for reference.
> > @nicks101 
> 
> Hey @HimeshNayak, this part is done.
> I'm fetching classes data from firestore and displaying them.
> I can't fetch for a particular college yet as we don't have reference ID for a collage right now. It's all dummy data.
> Should I open a PR so you can see the changes?
> 

Now plan to is add a screen where user can add his/her classes. Waiting for its UI.

**Comment by HimeshNayak** [comment]
> > I have seen that you have added the classes in the firestore. Please write a function to read the data from firestore and display it for the required college. You can view the similar function for homework for reference.
> > @nicks101
> 
> Hey @HimeshNayak, this part is done.
> I'm fetching classes data from firestore and displaying them.
> I can't fetch for a particular college yet as we don't have reference ID for a collage right now. It's all dummy data.
> Should I open a PR so you can see the changes?

yes, please open a PR. The changes then can be added in the same.
