### ISSUE TITLE
Add UserInfo model and collection to the App

### ISSUE THREAD

**Issue by Imadarshsri** [avinashkranjan/Friday#41]
In order to display the information in Profile Page, we need to collect the relevant information from the users and need to create a `User` model to hold them and also a `users` collection in Firestore for the same.

Tasks that need to be done:

- [ ] Create a `User` model/class with relevant attributes
- [ ] Create a `users` collection for saving user information
- [ ] Create a Form to be displayed while Onboarding/Signing up to collect the aforementioned information 
- [ ] Fetching information from `users` and displaying them on the Profile page.

I would like to work on this as it is related to the Profile Page, the issue which I'm currently working on.

**Comment by avinashkranjan** [comment]
Assigned to you @Imadarshsri
