### ISSUE TITLE
Feat: Making the contributors section dynamic

### ISSUE THREAD

**Issue by Viveksati5143** [avinashkranjan/Friday#415]
### Describe the feature

Making the contributors section dynamic in readme.md
The svg will look something like this with limit upto 54 contributors & will move from right to left.

### Add ScreenShots

![image](https://github.com/avinashkranjan/Friday/assets/100852245/b79e1fae-1f47-43ba-b51b-ee97995a24d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Not Needed, We Already have a contributors Section.

**Comment by Viveksati5143** [comment]
> Not Needed, We Already have a contributors Section.

Apologies for the misconception avinash... It is not a section I have added but a new feature to contributors section which is a dynamic svg of all the contributors decresing from contributors with most contributors to less.
And this is done using a new open-source tool called vaunt.
So, please reopen and merge the pr @avinashkranjan 
Thanks.
