### ISSUE TITLE
Adding Calender in Classes Page of the App #SWoC 2021

### ISSUE THREAD

**Issue by Imadarshsri** [avinashkranjan/Friday#43]
The classes Page does not have a calendar integrated into it. I would like to work on this by adding customizable calender.

**Comment by avinashkranjan** [comment]
Sure Go ahead @Imadarshsri

**Comment by ajay963** [comment]
17 days have passed ,
If nobody working on this feature  please assign this task to me

**Comment by avinashkranjan** [comment]
Sure Go Ahead @ajay963
