### ISSUE TITLE
[DOC]

### ISSUE THREAD

**Issue by skshrinaya** [avinashkranjan/Friday#438]
### What's wrong with the existing documentation

Hi I am a GSSOC'24 contributor. In this Documentation , You've given a link to friday application preview But it is showing 404 error page not found . Please check it out.

### Add ScreenShots

![Screenshot 2024-05-11 134902](https://github.com/avinashkranjan/Friday/assets/125351066/012d8dad-4b3a-4d1b-89cb-e0d5e496f82e)
![Screenshot 2024-05-11 134918](https://github.com/avinashkranjan/Friday/assets/125351066/2bc77525-c9b1-45e4-ac16-3ff28ab76873)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by avinashkranjan** [comment]
Project is not a Part of `GSSOC'24`
