### ISSUE TITLE
App logo not attached

### ISSUE THREAD

**Issue by hareshnayak** [avinashkranjan/Friday#5]
I can do that if assigned under #SWoc 2021

**Comment by avinashkranjan** [comment]
@hareshnayak Which logo are you talking about?

**Comment by hareshnayak** [comment]
the app logo (ic_launcher.png for android) is still the default flutter logo which should have been the app logo

**Comment by ShrutiJ-01** [comment]
I would be glad to work on this!I am a SWOC participant

**Comment by avinashkranjan** [comment]
@ShrutiJ-01 Since Issues are First Come First Serve.. This issue has been  assigned to @hareshnayak 
@hareshnayak Go ahead and add the app logo.

**Comment by ShrutiJ-01** [comment]
@avinashkranjan Sure👍👍 All the best @hareshnayak :)

**Comment by hareshnayak** [comment]
Thanks @avinashkranjan @ShrutiJ-01

**Comment by avinashkranjan** [comment]
Are you still working on this issue?? Or should I assign it to someone else?? @ShrutiJ-01

**Comment by avinashkranjan** [comment]
@ShrutiJ-01 Do You want to work on this issue???

**Comment by mysterio0801** [comment]
@avinashkranjan I would like to work on this.

**Comment by avinashkranjan** [comment]
Sure @mysterio0801 Go ahead

**Comment by mysterio0801** [comment]
> Sure @mysterio0801 Go ahead

Thanks @avinashkranjan

**Comment by avinashkranjan** [comment]
Any Updates @mysterio0801
