### ISSUE TITLE
LOGO DESIGN

### ISSUE THREAD

**Issue by kanchi12P** [avinashkranjan/Friday#56]
I would like to make a logo for this project.
so, can I go for it?
I am GSSoC'21 participant.
please assign it to me.

**Comment by avinashkranjan** [comment]
Go Ahead @kanchi12P Assigning it to you

**Comment by kanchi12P** [comment]
Thanks for assigning 
I will be submitting logo soon 
Its almost ready

**Comment by SpecTEviL** [comment]
Hey @avinashkranjan, Vishal Patil here, and I would like to try this issue under GSSoC'21. To view my previous work you can visit https://spectevil.github.io. Also, my Github profile logo is made by me hence I have experience of working with logos.
If you can assign this issue to me as well it would be great.
Thanks!

**Comment by kanishkaa24** [comment]
Hello! Can I work on this?

**Comment by abhishree07** [comment]
Hello, I would love to contribute to this issue. Kindly assign it to me

**Comment by rajeshpanjiyar** [comment]
I want to work on this. I am a participant in GSSoC'21. 
*I think this issue should have open for all tags and the best logo should be merged. Is this so?*

**Comment by rajeshpanjiyar** [comment]
Hi, Can I work on this? I am a **GSSoC'21** participant. Can I be assigned?

**Comment by shreya-gb** [comment]
Hello, I am really eager to work on this logo and solving the issues. But, I am not able to understand how to. Kindly guide.

**Comment by avinashkranjan** [comment]
@SpecTEviL @kanishkaa24 @abhishree07 @shreya-gb Anyone would like to work on the Logo.. Issue would be `FCFS`..

**Comment by kanchi12P** [comment]
@avinashkranjan I was engaged in my semester exams and they are over today I will continue today working in this please assign me again

**Comment by abhishree07** [comment]
I am more than happy to work on the logo. Kindly assign me the task. I will
get started on it right away.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by aman339** [comment]
I have also created and design Logo for Friday have a look at this. @avinashkranjan 
![F R I D A Y (6)](https://user-images.githubusercontent.com/66405145/115138423-aff41d80-a049-11eb-878e-5c4fb73a3bce.png)
![F R I D A Y (7)](https://user-images.githubusercontent.com/66405145/115138427-b97d8580-a049-11eb-96de-e3f5dc159a49.png)

**Comment by aman339** [comment]
if These logo is perfect then assign me this issue under Gssoc.
or if u want me to just make another one then also let me know. @avinashkranjan

**Comment by alphaX86** [comment]
Logo actually looks good! But let's see what the PA says... Then we can proceed

**Comment by aman339** [comment]
Ok Sir @alphaX86

**Comment by avinashkranjan** [comment]
Hey Aman, Keep the Logo Simple..Don't Put App Name in the Logo..cause when the size of the logo would decrease it would get distorted, Try Something Simple but Elegant which matches the theme of the app..

**Comment by aman339** [comment]
okay sir :) @avinashkranjan .
look at this.
![Friday_logodesign_1 (1)](https://user-images.githubusercontent.com/66405145/115617129-a3ecb200-a30e-11eb-9b8e-67a769d10322.png)

let me know if it may have changes and i am also working on another one friday's logo.

**Comment by alphaX86** [comment]
It looks nice than the previous one! ❤️

**Comment by aman339** [comment]
> It looks nice than the previous one! ❤️

Thank you sir @alphaX86

**Comment by avinashkranjan** [comment]
Hey @aman339 This is looks better, Do you have any alternatives too to show?

**Comment by aman339** [comment]
yes @avinashkranjan  . and sorry for late joining i have my exams so thats why i am not active at that time.

![Friday_logodesign_2](https://user-images.githubusercontent.com/66405145/116775561-27ca3b00-aa81-11eb-8522-085c67ec9aa5.png)
![Friday_design_3](https://user-images.githubusercontent.com/66405145/116775562-2a2c9500-aa81-11eb-8131-afd5ce7cd594.png)

**Comment by SKV-programmer** [comment]
I would like to work on this issue, @avinashkranjan kindly assign me this.

**Comment by avinashkranjan** [comment]
Sure @SKV-programmer , I'll Select the Best out of all these logos

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @harshsingh32, Assigning it to you..
