### ISSUE TITLE
Google Authentication Through Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#58]
Hello @avinashkranjan, I  would like to add Google Authentication through firebase in this project...... I noticed that you already assigned email and password authentication to this project but not google authentication....... If I can forward with this, please gives me permission and assign me to here... I am also a **_gssoc21_**  participant... Thank you @avinashkranjan .....

**Comment by avinashkranjan** [comment]
Go Ahead @SamarpanCoder2002 
You need access to Firebase for that, Kindly DM me on discord for that will giv you access to firebase.

**Comment by SamarpanCoder2002** [comment]
> Go Ahead @SamarpanCoder2002
> You need access to Firebase for that, Kindly DM me on discord for that will giv you access to firebase.

Ok

**Comment by SamarpanCoder2002** [comment]
> Go Ahead @SamarpanCoder2002
> You need access to Firebase for that, Kindly DM me on discord for that will giv you access to firebase.

I already added that functionality and added pull request related to that here(https://github.com/avinashkranjan/Friday/pull/70#issue-591184091)...Please check it out and merge it....If there is any problem, You can freely tell me.....Thanks for give me that chance to add this functionality

**Comment by SamarpanCoder2002** [comment]
> > Go Ahead @SamarpanCoder2002
> > You need access to Firebase for that, Kindly DM me on discord for that will giv you access to firebase.
> 
> I already added that functionality and added pull request related to that here([#70 (comment)](https://github.com/avinashkranjan/Friday/pull/70#issue-591184091) check it out and merge it....If there is any problem, You can freely tell me.....Thanks for give me that chance to add this functionality

I already made changes according to your instruction @HimeshNayak .... Please check it out and merge it, if there no problem....else you can freely tell me
