### ISSUE TITLE
add a progress graph 

### ISSUE THREAD

**Issue by starlightknown** [avinashkranjan/Friday#64]
Can we add a progress graph so that we can track our marks and work according to that?

**Comment by avinashkranjan** [comment]
Would you like to work on that issue? @kcoder63

**Comment by believeInJha** [comment]
I would like to work on this as a part of GSSoC'21, could you please assign it to me and guide me with the process?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @believeInJha

**Comment by believeInJha** [comment]
Thanks for the opportunity @avinashkranjan , I will make it as soon as possible and send a PR.

**Comment by HimeshNayak** [comment]
Any updates? @believeInJha

**Comment by nicks101** [comment]
Where do you want to show the progress bar(on which screen)?
And we are not handling marks anywhere, so what should be the criteria to track the progress bar?

**Comment by Ronak8602** [comment]
Hey @avinashkranjan @nicks101 We can have a progress graph right at the top of Recent Alerts . I can create that can I work on this issue

**Comment by avinashkranjan** [comment]
Can I see a prototype of the suggested feature?

**Comment by Utkarsh4517** [comment]
I would love to work on this issue, can you please assign this to me. GSSOC 23 @avinashkranjan

**Comment by Uttkarsh-raj** [comment]
hii @avinashkranjan  I would like to contribute to this project and this issue can you assign this to me ....

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by rafiya2003** [comment]
please assign this issue to me under GSSoC'23

**Comment by Khushal747** [comment]
i can do this using sparkline library  so that students can see their progress please assign me this issue under GSSOC'23

**Comment by avinashkranjan** [comment]
Go Ahead @harshsingh32, 

Since I've already assigned multiples issues to you, Kindly Complete them as soon as possible. Else there are many other contributors as well we are looking to contribue.

**Comment by Gitesg** [comment]
if this issue is not resolved  then asssign me this?

**Comment by avinashkranjan** [comment]
Go Ahead @Gitesg

**Comment by andoriyaprashant** [comment]
Could you please hand over this issue to me,  @avinashkranjan sir? I have already started working on it, and I will soon open a pull request for it. Please assign me this issue.

**Comment by andoriyaprashant** [comment]
Hello @avinashkranjan Please review my pull request #329 
Thank you

**Comment by Gitesg** [comment]
ok
