### ISSUE TITLE
Add obscure password option in login/signup page

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#67]
**Is your feature request related to a problem? Please describe.**
User cannot view the password he/she has entered.

**Describe the solution you'd like**
Toggle button can be added to show and hide password  

**Describe alternatives you've considered**
Any other suggestions are welcomed.

**Additional context**
Participants of GSSOC21 willing to work on this issue can comment here and I will assign it to you.

**Comment by D-Ajay-Kumar** [comment]
Can I do it? GSSoC participant

**Comment by HimeshNayak** [comment]
sure, go ahead @D-Ajay-Kumar

**Comment by D-Ajay-Kumar** [comment]
Thanks. Working on it.

**Comment by D-Ajay-Kumar** [comment]
There already is an Icon at the end of the text field. Where do you propose I add a new IconButton to turn the obscurity on and off?

**Comment by HimeshNayak** [comment]
I guess, the suffix button in the field should be used as the toggle button. You can add the functionality to it only and change the icon accordingly.

**Comment by D-Ajay-Kumar** [comment]
Okay Boss! On it.

**Comment by D-Ajay-Kumar** [comment]
The AuthInputField widget was created separately to avoid repeating the decoration right? If that is the case then I have a cleaner method of doing the same without having to repeat the decoration code using .copyWith() method and moving the decoration to  the constant file. Not only will this remove a separate file dedicated to the textfield but it will also make things easier and faster as so many values won't be needed to be sent to the current AuthInputField. Should I do it this way?

**Comment by HimeshNayak** [comment]
Use AuthInputField only. You can create a IconButton in AuthInputField similar to suffixIcon and add its working accordingly.

**Comment by D-Ajay-Kumar** [comment]
Done as you wanted it to be. Please check the code :)
