### ISSUE TITLE
Add image picker to profile_screen

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#68]
**Profile Image of the user**
Add image picker to the profile_screen, store the image in the Firebase Storage and display the image accordingly where ever it is called. 

Participants of GSSOC21 willing to work on this issue can comment here and I will assign it to you.

If you need any assistance / guidance, do tell.

**Comment by seadhant** [comment]
assign it to me, i can do it

**Comment by HimeshNayak** [comment]
> assign it to me, i can do it

sure, go ahead @seadhant

**Comment by D-Ajay-Kumar** [comment]
In case the current assignee fails, I can do it.

**Comment by seadhant** [comment]
> > assign it to me, i can do it
> 
> sure, go ahead @seadhant

is there any google-services json file I need to add, bcoz its showing gradle failure

**Comment by HimeshNayak** [comment]
@D-Ajay-Kumar If you want to work on this issue, kindly comment. Else it would be assigned to someone else who wants to work on this.

**Comment by D-Ajay-Kumar** [comment]
Yeah sure I'll do it

**Comment by HimeshNayak** [comment]
Okay, I'll assign it to you.

**Comment by D-Ajay-Kumar** [comment]
The image picker is added, images are getting picked, images are being stored in firebase storage, the image is being uploaded on the app after picking on both home and profile screen but when I try to upload this updated User model on firestore to update the profilePictureUrl there using the already created addUserToDatabase method it sends a verification email coz the method has been coded that way. Should I create an new method to upload the user doc on firestore to update the profilePictureUrl or what? Also, the image should be picked from camera or gallery?

**Comment by HimeshNayak** [comment]
You can code a method specifically for updating the profile picture. And choose the picture from gallery for now.
