### ISSUE TITLE
Facebook Authentication Through Firebase

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#71]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to add Facebook Authentication Through Firebase Here

**Describe alternatives you've considered**
Google and email-password authentication already added but not facebook authentication..... I would like to add this.....

**Additional context**
I already make a Google Authentication pull request here..... I have experience in that kind of authentication.... I think I can do it.....
If I can forward with that.....Please assign me to here....Thanks

**Comment by HimeshNayak** [comment]
Facebook Auth can be implemented. I am assigning this issue to you.
Also have a look on the changes requested in google auth PR, code this similarly.

**Comment by SamarpanCoder2002** [comment]
> Facebook Auth can be implemented. I am assigning this issue to you.
> Also have a look on the changes requested in google auth PR, code this similarly.

Thanks for assigning me here... First I change in google Auth Pull Request and after merge of that I will start working on facebook auth.... Thanks for review my google auth Pull request.... I surely make changes soon....Thank you
