### ISSUE TITLE
Wiki Page

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#76]
Create a Wiki Page for the project.

Anyone who wants to work on this issue under GSSOC21, comment here and I'll assign it to you.
You can refer : https://guides.github.com/features/wikis/ for getting more info on Wiki Pages.

**Comment by SamarpanCoder2002** [comment]
> Create a Wiki Page for the project.
> 
> Anyone who wants to work on this issue under GSSOC21, comment here and I'll assign it to you.
> You can refer : https://guides.github.com/features/wikis/ for getting more info on Wiki Pages.

Hello @HimeshNayak , I want to work with it..... Can you give me a sample idea, how I can design Wiki page for that project...I already gathered knowledge on github wiki.... Thanks

**Comment by avinashkranjan** [comment]
Hey @SamarpanCoder2002 

Create a Wiki Page for this project describing:

- What this Project is?
- Purpose of this Project
- Issues it would solve
- Short and Precise description of all Features, this app currently has.

You can check the guide material:

- [Writing and Formatting on GitHub](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- [Wiki page](https://guides.github.com/features/wikis/)

**Comment by HimeshNayak** [comment]
I have created the wiki page. Here is the link
https://github.com/avinashkranjan/Friday/wiki
@SamarpanCoder2002 you can add content to it as described by @avinashkranjan

**Comment by SamarpanCoder2002** [comment]
> Hey @SamarpanCoder2002
> 
> Create a Wiki Page for this project describing:
> 
> * What this Project is?
> * Purpose of this Project
> * Issues it would solve
> * Short and Precise description of all Features, this app currently has.
> 
> You can check the guide material:
> 
> * [Writing and Formatting on GitHub](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github)
> * [Wiki page](https://guides.github.com/features/wikis/)

Thanks @HimeshNayak  @avinashkranjan for give me that sample.... I will start work on it soon

**Comment by SamarpanCoder2002** [comment]
Hello @avinashkranjan @HimeshNayak , I already made Wiki pages for this project.... But I don't understand how to make a pull request about this wiki pages..... Should I put the `md` file as one of project file and then make pull request or not???? Please let me know.... Here's my wiki pages: https://github.com/SamarpanCoder2002/Friday.wiki.git

Thanks  u @HimeshNayak @avinashkranjan

**Comment by HimeshNayak** [comment]
Yes, add it in a md file and submit the PR mentioning this issue.

**Comment by SamarpanCoder2002** [comment]
> Yes, add it in a md file and submit the PR mentioning this issue.

sure
