### ISSUE TITLE
Designing and implementing UI of Profile Page #SWoC 2021

### ISSUE THREAD

**Issue by hareshnayak** [avinashkranjan/Friday#8]
The top bar consists of a Profile icon. It could be tapped to open the details of the user like a profile page. I would like to make that as an Animated Overlay which will consist of  name, class of the user with a profile picture 

I will be happy to design the profile overlay under SWoC 2021

**Comment by avinashkranjan** [comment]
Assigned to you.. @hareshnayak

**Comment by avinashkranjan** [comment]
@hareshnayak Should I ask fellow contributors to design the page then you can code or you're going to both design and code?

**Comment by hareshnayak** [comment]
I can do both,
Let me send the PR first, if u find that there should be a different approach to it, u may give the design work to someone.

But let me first design n send the PR

**Comment by avinashkranjan** [comment]
Sure Sure

**Comment by purnima143** [comment]
## Design for profile page
![profilee](https://user-images.githubusercontent.com/57852378/104844860-887d9f80-58f8-11eb-99b7-487ebb46ba3d.png)

**Comment by avinashkranjan** [comment]
@hareshnayak Once I confirm the Design you can start working on it.. so, wait for me to Confirm the design..

**Comment by hareshnayak** [comment]
Yes, sure

**Comment by purnima143** [comment]
![Profile page2](https://user-images.githubusercontent.com/57852378/104871672-b6eb9100-5971-11eb-860d-98701db5bed6.png)

**Comment by purnima143** [comment]
@avinashkranjan  Please check out the new design

**Comment by avinashkranjan** [comment]
> @avinashkranjan Please check out the new design

This Looks Good..@hareshnayak Go ahead with this design and start working on it's Implementation..

**Comment by hareshnayak** [comment]
great!

**Comment by avinashkranjan** [comment]
Any Updates @hareshnayak ???

**Comment by avinashkranjan** [comment]
Are you working on this issue or should I assign it to someone else?? @hareshnayak

**Comment by Imadarshsri** [comment]
@avinashkranjan... If nobody is working on it, Can I take this issue??

**Comment by avinashkranjan** [comment]
Go Ahead @Imadarshsri while you're on it change the `Hello, Sir` to `Hello, Username`

**Comment by Imadarshsri** [comment]
Thanks...I will do it...
