### ISSUE TITLE
Email and Password Authentication Added but not Registered Email Verification

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#81]
**Is your feature request related to a problem? Please describe.**
yes..... Email and Password Verification added already but not registered email verification...... Suppose someone signup as 'g@mail.com'... If there presents no such email, then a fake user can use this application..... So unethical activity can be performed through that..... So I want to add Email and password Verification...

**Describe the solution you'd like**
When users signup with an email and password, A verification Link Will send to the registered email.... After verifying the registered email through the link(send to registered email via firebase), User only can log in to the application..... (This feature is only for email and password auth not for google or Facebook auth because their authentication is done by default)..... This will make this app more authentic...

**Describe alternatives you've considered**
I think the above process is very good for the sake of auth...

**Additional context**
I am also a GSSOC'21 participant.... If I can forward with that.... Please assign me to here.... Thanks, @avinashkranjan @HimeshNayak

**Comment by avinashkranjan** [comment]
Go Ahead @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
> Go Ahead @SamarpanCoder2002

Thanks for assigning me.... I will work on that very soon

**Comment by SamarpanCoder2002** [comment]
> Go Ahead @SamarpanCoder2002

I already made a pull request regarding to that @HimeshNayak @avinashkranjan .... please review it and merge it.....
