### ISSUE TITLE
Google Sign In Not Working

### ISSUE THREAD

**Issue by SapinderSingh** [avinashkranjan/Friday#83]
**Describe the bug**
When I clicked on Google Sign In button and chose the account, an Exception came.

**To Reproduce**
1. Start the app
2. Click on Google SignIn button.
3. Choose your account.
4. See the exception.

**Expected behavior**
It should SignIn and go the next screen.

**Screenshots**
![Screenshot 2021-03-13 125125](https://user-images.githubusercontent.com/29424616/111022768-e57a6b00-83fa-11eb-909c-8397e113d07e.png)

**Comment by HimeshNayak** [comment]
Hi @SapinderSingh. The firebase project should have the SHA-1 certificate registered for the google sign in to work on the emulator/device. The Google sign in is working fine and is reviewed by me and @avinashkranjan.

You can look here for more reference
https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application 

For now I am closing this issue. If the error still occurs comment here and we will try to resolve it then.
Also if there's any suggestion / guidance needed to tell.
