### ISSUE TITLE
Bottom Padding of the Logout Button

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#84]
The Logout button has very less bottom padding, and thus it is not visible to the user even after scrolling.

Increase the padding.

![Screenshot_20210313_225436](https://user-images.githubusercontent.com/30944790/111038520-82ff8a00-844f-11eb-91bf-a3d2ec18050c.png)

If anyone wants to work on this under GSSOC21, comment here, I'll assign you.

**Comment by D-Ajay-Kumar** [comment]
Can do it

**Comment by HimeshNayak** [comment]
go head @D-Ajay-Kumar

**Comment by D-Ajay-Kumar** [comment]
On it
