### ISSUE TITLE
Heading not fitted on screen(in Bottom Navigation Screen ) when user name is too long

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#87]
**Is your feature request related to a problem? Please describe.**
Bottom_Navigation.dart file, heading not fitted on screen when user name is too long....

**Describe the solution you'd like**
I want to add flexibility in that heading... I attach a picture below about the problem....Please take a look here
<img src="https://user-images.githubusercontent.com/66327336/111042109-ad5a4300-8461-11eb-8677-cc012f26c95d.png" alt="problem image" width="200">

**Describe alternatives you've considered**
Add Flexibility in heading with the user name

**Additional context**
If I can forward With that, Please assign me to here... I am also a gssoc'21 participant... I will surely fix that problem...Thank you

**Comment by HimeshNayak** [comment]
Hi @SamarpanCoder2002. This is a valid issue and should be worked upon. But since you already have 3 pending PRs, please let this issue be solved by other participants. 
If no other participant wants to work on this issue till the time you submit 1-2 PRs, I'll assign it to you.

Thus this issue is available for grab. If any GSSOC21 participant wants to work on it, please comment and I'll assign it to you.

**Comment by Aishani2001** [comment]
Hello @HimeshNayak please assign this issue to me sir.

**Comment by HimeshNayak** [comment]
sure, go ahead @Aishani2001. I'll assign it to you.

**Comment by Ruhika1417** [comment]
hi could you assign this to me?

**Comment by HimeshNayak** [comment]
Hi @Ruhika1417 The issue has already been assigned to @Aishani2001. If she fails to resolve the issue. I'll assign it to you.

**Comment by Ruhika1417** [comment]
OK @HimeshNayak

**Comment by HimeshNayak** [comment]
@Aishani2001 Any updates?

**Comment by Ruhika1417** [comment]
Hi @HimeshNayak let me know if I could take this up or not...

**Comment by HimeshNayak** [comment]
Since @Aishani2001 has not responded, I am assigning this issue to @Ruhika1417 .
