### ISSUE TITLE
landing page content override in physical device

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#88]
**Is your feature request related to a problem? Please describe.**
landing page content override in physical device

**Describe the solution you'd like**
In physical device, Landing page content override to each other.... I attach examples below...take a look here.....
<p>
<img src="https://user-images.githubusercontent.com/66327336/111042819-3b83f880-8465-11eb-91a7-51984e7fe4d2.png" alt="emulator picture" width="200">
<img src="https://user-images.githubusercontent.com/66327336/111042865-77b75900-8465-11eb-845b-6254c31b0a7c.jpeg" alt="Physical Device Picture" width="200">
</p>
<p>Emulator Picture---------------------Physical Device Picture</p>

**Describe alternatives you've considered**
This is due to positioned widget.... I will make it more responsive to have a better look in physical device.

**Additional context**
If I can forward with that, Please assign me to here...... I am also a gssoc'21 participant... Thank you

**Comment by HimeshNayak** [comment]
Hi @SamarpanCoder2002. This is a valid issue and should be worked upon. But since you already have 3 pending PRs, please let this issue be solved by other participants.
If no other participant wants to work on this issue till the time you submit 1-2 PRs, I'll assign it to you.

Thus this issue is available for grab. If any GSSOC21 participant wants to work on it, please comment and I'll assign it to you.

**Comment by Aishani2001** [comment]
Hello @HimeshNayak I would like to work on this issue. Please assign it to me.

**Comment by HimeshNayak** [comment]
sure, go ahead @Aishani2001, I'll assign it to you.

**Comment by HimeshNayak** [comment]
Any updates @Aishani2001 ?

**Comment by Aishani2001** [comment]
Sir i’m working on it.

**Comment by Ruhika1417** [comment]
Hi @HimeshNayak, I would like to fix this issue. could you please follow up  w other participants if they're working or not on this...

**Comment by Ruhika1417** [comment]
Hi @HimeshNayak , I would like to work on this. could you please follow up w other participants if they're working on this or not...

**Comment by HimeshNayak** [comment]
It has been too long! I am assigning this issue to you @Ruhika1417.

**Comment by Udit-singh** [comment]
@HimeshNayak Since its been no response from assignee, I would like to work upon this issue under gssoc'21,
And I will be opening a PR within 24 hours.

**Comment by Ruhika1417** [comment]
@HimeshNayak I'm working on this...

**Comment by Inventor77** [comment]
@HimeshNayak Please Mentor let me Work on this issue I'm having some sort of Idea why this is happening I will solve it within few hours

**Comment by Udit-singh** [comment]
> @HimeshNayak Since its been no response from assignee, I would like to work upon this issue under gssoc'21,
> And I will be opening a PR within hours.

I have Requested before, I also know the reason of the issue , I can also solve it within few hours.
@HimeshNayak Please assign it to me.

**Comment by HimeshNayak** [comment]
Go ahead! @Udit-singh
