### ISSUE TITLE
Current Academic Year Keyboard type restriction not added

### ISSUE THREAD

**Issue by SamarpanCoder2002** [avinashkranjan/Friday#93]
**Is your feature request related to a problem? Please describe.**
Look at the picture
<img src="https://user-images.githubusercontent.com/66327336/111146533-8f025d80-85af-11eb-8547-cd51eb9dc352.png" width="200">

Current academic year should be number..... but keyboard came as text but not as only number keyboard

**Describe the solution you'd like**
For only that case, I would like to introduce number keyboard instead of text keyboard

**Additional context**
I want to add the above solution in that....
If I can proceed with that, please assign me to here ..... I am also a gssoc'21 participant..... Thank you @avinashkranjan @HimeshNayak

**Comment by hs2361** [comment]
@HimeshNayak @avinashkranjan I'm a GSSoC'21 participant. Can you please assign me to this issue?

**Comment by D-Ajay-Kumar** [comment]
@HimeshNayak  @SamarpanCoder2002 also just a small correction, it'd be better to change the word from 'Course' to 'Degree'. Course is a lil confusing.

**Comment by SamarpanCoder2002** [comment]
> @HimeshNayak @SamarpanCoder2002 also just a small correction, it'd be better to change the word from 'Course' to 'Degree'. Course is a lil confusing.

Better option.... Waiting for the response @HimeshNayak

**Comment by namancoder** [comment]
But anything other than number is not accpeted i think ,so their is no need because switching keyboard from full to only numeric is also not very intuitive.
it maintains the flow of filling the form.

**Comment by HimeshNayak** [comment]
Great issue @SamarpanCoder2002, go ahead and fix it, I'll assign it to you!

**Comment by HimeshNayak** [comment]
Also degree and course depend on the institute. Leave it as it is for now. We are planning to change this page a little and this can be done there.

**Comment by SamarpanCoder2002** [comment]
> Also degree and course depend on the institute. Leave it as it is for now. We are planning to change this page a little and this can be done there.

ok...I will change only keyboard issue

**Comment by SamarpanCoder2002** [comment]
> Also degree and course depend on the institute. Leave it as it is for now. We are planning to change this page a little and this can be done there.

I already make a pull request regarding to that....pls check it out @HimeshNayak @avinashkranjan
