### ISSUE TITLE
Design and implement a page to register college

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#94]
**Is your feature request related to a problem? Please describe.**
Yes, multiple users enter different strings for college details, which creates an ambiguity in the database. Design a page to register college so that it can be added in classes collection.

**Describe the solution you'd like**
The page should check if any class is already present with the same configuration or not and then create it if it is not there.
![image](https://user-images.githubusercontent.com/30944790/111192274-e4099800-85de-11eb-91bb-ea15c6d97087.png)

**Additional context**
Register college option should be given in the signup page such that if the user doesn't find the college details in the dropdown then he/she can register their college.

Anyone willing to work on this issue under GSSOC21 may comment below and I'll assign it to you. If you need more explanation / guidance, do tell.

**Comment by D-Ajay-Kumar** [comment]
I guess I'll need a lil more info. Super interested in working in it.

**Comment by D-Ajay-Kumar** [comment]
So if the user fails to find his college in the drop-down then he goes to this screen to manually enter his college. Is that what it is?

**Comment by HimeshNayak** [comment]
> So if the user fails to find his college in the drop-down then he goes to this screen to manually enter his college. Is that what it is?

Yes, if the user fails to find his college in the drop-down, then he would go to this page and register the college so that it can be found in the dropdown.

**Comment by D-Ajay-Kumar** [comment]
Btw this issue is still open, I wanted more clarity on another issue related to this so commented.

**Comment by SamarpanCoder2002** [comment]
> > Btw this issue is still open, I wanted more clarity on another issue related to this so commented.
> 
> Okay! Anyone who wants to work on this issue please comment here.

I want to work here,.....assign me

**Comment by HimeshNayak** [comment]
Go ahead @SamarpanCoder2002 ! I'll assign it to you.

**Comment by SamarpanCoder2002** [comment]
> Go ahead @SamarpanCoder2002 ! I'll assign it to you.

Thanks @HimeshNayak

**Comment by SamarpanCoder2002** [comment]
I want to discuss something about that issue.....can I continue that on discord???

**Comment by HimeshNayak** [comment]
> I want to discuss something about that issue.....can I continue that on discord??? @HimeshNayak

yes sure @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
> > I want to discuss something about that issue.....can I continue that on discord??? @HimeshNayak
> 
> yes sure @SamarpanCoder2002

Can I continue fetch college name api use through that issue @HimeshNayak

**Comment by HimeshNayak** [comment]
Yes, go ahead.

**Comment by HimeshNayak** [comment]
Issue extended to #112
