### ISSUE TITLE
Replace TextField with dropdown in signup for college details

### ISSUE THREAD

**Issue by HimeshNayak** [avinashkranjan/Friday#95]
**Is your feature request related to a problem? Please describe.**
To reduce the ambiguity of college entries in the database. Only registered colleges should appear for the user to select when signing up in the app.

**Describe the solution you'd like**
Replace TextField with dropdown in signup for college details so that the user can select the details from there.
The registered colleges will have the following database.
![image](https://user-images.githubusercontent.com/30944790/111193495-38f9de00-85e0-11eb-8096-94c75d3c9e0d.png)

**Additional context**
Open to suggestions. Anyone willing to work on this issue under GSSOC21 may comment below and I'll assign it to you. If you need more explanation / guidance, do tell.

**Comment by D-Ajay-Kumar** [comment]
The data for the drop-down should be fetched from Firebase?

**Comment by HimeshNayak** [comment]
> The data for the drop-down should be fetched from Firebase?

Yes, you can use a StreamBuilder or FutureBuilder

**Comment by D-Ajay-Kumar** [comment]
I can try my hand at this, can I please?

**Comment by HimeshNayak** [comment]
> I can try my hand at this, can I please?

Yes sure, go ahead @D-Ajay-Kumar ! I'll assign this to you.

**Comment by D-Ajay-Kumar** [comment]
Where can i find the google services file?

**Comment by HimeshNayak** [comment]
Its already in the repo. https://github.com/avinashkranjan/Friday/blob/master/android/app/google-services.json

**Comment by D-Ajay-Kumar** [comment]
yup found it

**Comment by D-Ajay-Kumar** [comment]
The stream/future builder will wrap the whole form and till the data loads I should a circular progress indicator right?

**Comment by HimeshNayak** [comment]
> The stream/future builder will wrap the whole form and till the data loads I should a circular progress indicator right?

Yes.

**Comment by D-Ajay-Kumar** [comment]
Okay thank you very much.

**Comment by D-Ajay-Kumar** [comment]
![WhatsApp Image 2021-03-16 at 7 24 19 PM](https://user-images.githubusercontent.com/56850266/111322520-08bd4880-868f-11eb-9dfb-57d43ae8b4d7.jpeg)
![WhatsApp Image 2021-03-16 at 7 36 17 PM](https://user-images.githubusercontent.com/56850266/111322538-0ce96600-868f-11eb-8db0-9bbb02e61884.jpeg)
![WhatsApp Image 2021-03-16 at 7 36 17 PM (1)](https://user-images.githubusercontent.com/56850266/111322558-11158380-868f-11eb-81c4-ee80e71a0968.jpeg)

How do these look?

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)

**Comment by SamarpanCoder2002** [comment]
> Done. Please check the code :)

Good work bro

**Comment by D-Ajay-Kumar** [comment]
> Good work bro

Thanks man!
