### ISSUE TITLE
Content is overlapping

### ISSUE THREAD

**Issue by ishanailwal** [avinashkranjan/Friday#98]
![Screenshot_1615918407](https://user-images.githubusercontent.com/56601364/111365178-2d79e600-86b8-11eb-885e-0d2f25ae6c13.png)

"Sign Up" button is covering text. Can I work on rectifying this?

**Comment by SamarpanCoder2002** [comment]
> "Sign Up" button is covering text. Can I work on rectifying this?

This issue already raised in #88 and assigned to otherone...... Please close it....

**Comment by HimeshNayak** [comment]
Repeated Issue
